# Project : Evaluate Cars Condition based on given feature


- buying	Feature	Categorical		buying price	
- maint	Feature	Categorical		price of the maintenance	
- doors	Feature	Categorical		number of doors	
- persons	Feature	Categorical		capacity in terms of persons to carry		
- lug_boot	Feature	Categorical		the size of luggage boot		
- safety	Feature	Categorical		estimated safety of the car		
- class	Target	Categorical		evaulation level (unacceptable, acceptable, good, very good)	


##### based on this feature predict the car condition

### Step 1: Import Dependencies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.preprocessing import (LabelEncoder, 
                                   StandardScaler, 
                                   MinMaxScaler)

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (confusion_matrix, 
                             accuracy_score,
                             classification_report)

### Step 2: Load Dataset

In [2]:
df = pd.read_csv(r"cars.csv", header=None)
df.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
df.head()

  buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [3]:
df.shape

(1728, 7)

In [4]:
# check category level of all columns
for col in df.columns:
    print("----------------{}-----------------------".format(col))
    print(df[col].value_counts())
    print()

----------------buying-----------------------
buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

----------------maint-----------------------
maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

----------------doors-----------------------
doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64

----------------persons-----------------------
persons
2       576
4       576
more    576
Name: count, dtype: int64

----------------lug_boot-----------------------
lug_boot
small    576
med      576
big      576
Name: count, dtype: int64

----------------safety-----------------------
safety
low     576
med     576
high    576
Name: count, dtype: int64

----------------classes-----------------------
classes
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

in the above values counts we can see in two column we have category and numbers so we need to replace the categories with numbers using label encoder

### Step 3: Data Preprocessing

In [5]:
# check missing values
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

in the above data we can see there is no missing values

In [6]:
# check basic info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   classes   1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

we need to perform label encoder on all the columns bcoz all the columns contain object data type

In [7]:
# apply label encoder to convert categories into numeric values
le = LabelEncoder()

for x in df.columns:
    
    print(x)
    df[x]=le.fit_transform(df[x])
    le_name = dict(zip(le.classes_, le.transform(le.classes_)))
    print("--------------------------------------------------")
    print("Feature: ", x)
    print("Mapping: ", le_name)

buying
--------------------------------------------------
Feature:  buying
Mapping:  {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
maint
--------------------------------------------------
Feature:  maint
Mapping:  {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
doors
--------------------------------------------------
Feature:  doors
Mapping:  {'2': 0, '3': 1, '4': 2, '5more': 3}
persons
--------------------------------------------------
Feature:  persons
Mapping:  {'2': 0, '4': 1, 'more': 2}
lug_boot
--------------------------------------------------
Feature:  lug_boot
Mapping:  {'big': 0, 'med': 1, 'small': 2}
safety
--------------------------------------------------
Feature:  safety
Mapping:  {'high': 0, 'low': 1, 'med': 2}
classes
--------------------------------------------------
Feature:  classes
Mapping:  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}

In [8]:
df.head()

   buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

### Step 4: Seprate X and y

In [9]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [ ]:
# # USING FEATURE NAME FOR X AND Y 
# X = df[['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']]
# y = df["classes"]

In [10]:
X = df.iloc[  :  ,  :-1]  # independent variables
y = df.iloc[  :  ,   -1]  # dependent variable

### Step 5: Data Spliting

In [11]:
# Split the data into test and train
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3,
                                                    random_state=10)  
# verify spliting data
print("Total Data: ", df.shape)
print("Train X: ", X_train.shape)
print("Train y: ", y_train.shape)
print("Test X: ", X_test.shape)
print("Test y: ", y_test.shape)

Total Data:  (1728, 7)
Train X:  (1209, 6)
Train y:  (1209,)
Test X:  (519, 6)
Test y:  (519,)

### Step 6: Data Normalisation

In [12]:
# perform data normalisation

# create object for scaler
scaler = MinMaxScaler()

# fit the train data on scaler object 
scaler.fit(X_train)

X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)

Note: In this data set we can see all the values from all the columns and rows are ranging from 0 to 5 so there is no extreme high and low values so thats why we dont need to perfom standardsiation and normalisation

In [13]:
# compare normal and scale data
print(X_train.iloc[0])
print(X_train_scale[0])

buying      0
maint       0
doors       1
persons     2
lug_boot    0
safety      0
Name: 593, dtype: int32
[0.         0.         0.33333333 1.         0.         0.        ]

### Step 7: Build Model

#### 1. Decision Tree

In [14]:
# create model object  with default parameter 
model_dt = DecisionTreeClassifier()

# create model object  with custom parameter 
model_dt = DecisionTreeClassifier(criterion='gini',
                                  random_state=10, 
                                  min_samples_leaf=5, 
                                  min_samples_split=20,
                                  max_leaf_nodes=15,
                                  max_depth=6)

#fit the model on the data and predict the values
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [15]:
model_dt.get_depth()

14

In [16]:
# prediction on Test Data
y_pred= model_dt.predict(X_test)

# print(list(zip(y_test,y_pred)))

In [17]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[ 99   2   1   0]
 [  4  17   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

---------Accuracy Score------------
0.9845857418111753

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.89      0.81      0.85        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.98       519
   macro avg       0.96      0.94      0.95       519
weighted avg       0.98      0.98      0.98       519

## Tunned Dt model

In [18]:
# criterion='gini',
# splitter='best',
# max_depth=None,
# min_samples_split=2,
# min_samples_leaf=1,
# min_weight_fraction_leaf=0.0,
# max_features=None,
# random_state=None,
# max_leaf_nodes=None,
# min_impurity_decrease=0.0,
# class_weight=None,
# ccp_alpha=0.0,

model_dt2 = DecisionTreeClassifier(criterion='gini',
                                  random_state=10, 
                                  min_samples_leaf=10, 
                                  min_samples_split=2,
                                  max_leaf_nodes=30,
                                  max_depth=6)

#fit the model on the data and predict the values
model_dt2.fit(X_train, y_train)
print("Dept: ", model_dt2.get_depth())

# prediction on Test Data
y_pred2= model_dt2.predict(X_test)

# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred2))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred2))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred2))

Dept:  6
---------Confusion Matrix------------
[[ 81   0  13   8]
 [ 17   0   0   4]
 [ 19   0 352   0]
 [  0   0   0  25]]

---------Accuracy Score------------
0.882466281310212

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.69      0.79      0.74       102
           1       0.00      0.00      0.00        21
           2       0.96      0.95      0.96       371
           3       0.68      1.00      0.81        25

    accuracy                           0.88       519
   macro avg       0.58      0.69      0.63       519
weighted avg       0.86      0.88      0.87       519

C:\Users\Dev\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dev\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dev\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
# feature importance for all columns
# total will be 1 

print(list(zip(df.columns, model_dt.feature_importances_)))

In [ ]:
# from sklearn import tree
# import graphviz

# with open("model_DecisionTree.txt", "w") as f:
#     f = tree.export_graphviz(model_dt, feature_names=cars_df.columns[:-1], out_file=f)
    
# # generate the file and upload the code in webgraphviz.com to plot the decision tree

In [ ]:
df.columns[:-1]

In [ ]:
%%time

# it will take 5 to 6 mins to create image so wait.....
fig = plt.figure(figsize=(45,60)) 
dot_data = tree.plot_tree(model_dt, 
                   feature_names=list(df.columns[:-1]),  
                   class_names=list(df.columns[-1]),
                   filled=True)
plt.savefig("base_model1.jpeg")

In [ ]:
%%time

# it will take 5 to 6 mins to create image so wait.....
fig = plt.figure(figsize=(45,60)) 
dot_data = tree.plot_tree(model_dt2, 
                   feature_names=list(df.columns[:-1]),  
                   class_names=list(df.columns[-1]),
                   filled=True)
plt.savefig("tuned_model1.jpeg")

#### 2.  USING SVM

In [20]:
from sklearn import svm

In [22]:
# create svm object 
svc_model = svm.SVC()

# train svm model on train dataset
svc_model.fit(X_train, y_train)

# predict on test dataset
y_pred=svc_model.predict(X_test)

In [23]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[ 74   0  28   0]
 [ 14   5   0   2]
 [  4   0 367   0]
 [  6   0   0  19]]

---------Accuracy Score------------
0.8959537572254336

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.76      0.73      0.74       102
           1       1.00      0.24      0.38        21
           2       0.93      0.99      0.96       371
           3       0.90      0.76      0.83        25

    accuracy                           0.90       519
   macro avg       0.90      0.68      0.73       519
weighted avg       0.90      0.90      0.89       519

In [27]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
car_evaluation = fetch_ucirepo(id=19) 
  
# data (as pandas dataframes) 
X = car_evaluation.data.features 
y = car_evaluation.data.targets 
  
# metadata 
print(car_evaluation.metadata) 
  
# variable information 
print(car_evaluation.variables)

{'uci_id': 19, 'name': 'Car Evaluation', 'repository_url': 'https://archive.ics.uci.edu/dataset/19/car+evaluation', 'data_url': 'https://archive.ics.uci.edu/static/public/19/data.csv', 'abstract': 'Derived from simple hierarchical decision model, this database may be useful for testing constructive induction and structure discovery methods.', 'area': 'Other', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 1728, 'num_features': 6, 'feature_types': ['Categorical'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1988, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5JP48', 'creators': ['Marko Bohanec'], 'intro_paper': {'ID': 249, 'type': 'NATIVE', 'title': 'Knowledge acquisition and explanation for multi-attribute decision making', 'authors': 'M. Bohanec, V. Rajkovič', 'venue': '8th Intl Workshop on Expert Systems and their Applications, Avignon, France', 'year': 1988, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/KNOWLEDGE-ACQUISITION-AND-EXPLANATION-FOR-DECISION-Bohanec-Rajkovi%C4%8D/8bab443ae322ff47c3e609272bd93fd4650555bc', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Car Evaluation Database was derived from a simple hierarchical decision model originally developed for the demonstration of DEX, M. Bohanec, V. Rajkovic: Expert system for decision making. Sistemica 1(1), pp. 145-157, 1990.). The model evaluates cars according to the following concept structure:\r\n\r\nCAR                      car acceptability\r\n. PRICE                  overall price\r\n. . buying               buying price\r\n. . maint                price of the maintenance\r\n. TECH                   technical characteristics\r\n. . COMFORT              comfort\r\n. . . doors              number of doors\r\n. . . persons            capacity in terms of persons to carry\r\n. . . lug_boot           the size of luggage boot\r\n. . safety               estimated safety of the car\r\n\r\nInput attributes are printed in lowercase. Besides the target concept (CAR), the model includes three intermediate concepts: PRICE, TECH, COMFORT. Every concept is in the original model related to its lower level descendants by a set of examples (for these examples sets see http://www-ai.ijs.si/BlazZupan/car.html).\r\n\r\nThe Car Evaluation Database contains examples with the structural information removed, i.e., directly relates CAR to the six input attributes: buying, maint, doors, persons, lug_boot, safety.\r\n\r\nBecause of known underlying concept structure, this database may be particularly useful for testing constructive induction and structure discovery methods.\r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'buying:   vhigh, high, med, low.\nmaint:    vhigh, high, med, low.\ndoors:    2, 3, 4, 5more.\npersons:  2, 4, more.\nlug_boot: small, med, big.\nsafety:   low, med, high.', 'citation': None}}
       name     role         type demographic  \
0    buying  Feature  Categorical        None
1     maint  Feature  Categorical        None
2     doors  Feature  Categorical        None
3   persons  Feature  Categorical        None
4  lug_boot  Feature  Categorical        None
5    safety  Feature  Categorical        None
6     class   Target  Categorical        None

                                         description units missing_values
0                                       buying price  None             no
1                           price of the maintenance  None             no
2                                    number of doors  None             no
3              capacity in terms of persons to carry  None             no
4                           the size of luggage boot  None             no
5                        estimated safety of the car  None             no
6  evaulation level (unacceptable, acceptable, go...  None             no

In [ ]:
X = df[['sepal length', 'sepal width', 'petal length', 'petal width']]
y = df.Label

# Split the data into test and train
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3,
                                                    random_state=10)  

model_dt3 = DecisionTreeClassifier()

#fit the model on the data and predict the values
model_dt3.fit(X_train, y_train)
print("Dept: ", model_dt3.get_depth())

# prediction on Test Data
y_pred3= model_dt3.predict(X_test)

# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred3))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred3))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred3))

In [ ]:
%%time

# it will take 5 to 6 mins to create image so wait.....
fig = plt.figure(figsize=(45,60)) 
dot_data = tree.plot_tree(model_dt3, 
                   feature_names=list(df.columns[:-1]),  
                   class_names=list(df.columns[-1]),
                   filled=True)
plt.savefig("tuned_model3.jpeg")

# Bagging Approach

**Running Bagging Classifier model**

In [24]:
from sklearn.ensemble import BaggingClassifier

In [25]:
#predicting using the Bagging_Classifier
model = BaggingClassifier(n_estimators=50, random_state=10) 

# try to increase the n_estimator  # min_samples_leaf=1, max_depth=None

#fit the model on the data and predict the values
model = model.fit(X_train,y_train)

y_pred=model.predict(X_test)

In [26]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[102   0   0   0]
 [  1  20   0   0]
 [  2   0 369   0]
 [  1   0   0  24]]

---------Accuracy Score------------
0.9922928709055877

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       102
           1       1.00      0.95      0.98        21
           2       1.00      0.99      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.98      0.98       519
weighted avg       0.99      0.99      0.99       519

**Running Random Forest model**

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
%%time 

#predicting using the Random_Forest_Classifier
model_rf = RandomForestClassifier(n_estimators=100, 
                                          random_state=10,
                                         verbose=0,
                                        n_jobs=-1)

#fit the model on the data and predict the values
model_rf.fit(X_train,y_train)

y_pred = model_rf.predict(X_test)

CPU times: total: 62.5 ms
Wall time: 331 ms

In [46]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[ 99   3   0   0]
 [  3  18   0   0]
 [  2   0 369   0]
 [  2   0   0  23]]

---------Accuracy Score------------
0.9807321772639692

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       102
           1       0.86      0.86      0.86        21
           2       1.00      0.99      1.00       371
           3       1.00      0.92      0.96        25

    accuracy                           0.98       519
   macro avg       0.95      0.94      0.94       519
weighted avg       0.98      0.98      0.98       519

# Boosting Classifier

**Running Adaboost classifier**

In [47]:
from sklearn.ensemble import AdaBoostClassifier

In [50]:
#predicting using the AdaBoost_Classifier
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),
                                 n_estimators=90)

#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,y_train)

y_pred=model_AdaBoost.predict(X_test)

C:\Users\Dev\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

In [51]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[100   1   1   0]
 [  3  18   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

---------Accuracy Score------------
0.9884393063583815

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       102
           1       0.95      0.86      0.90        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.98      0.95      0.96       519
weighted avg       0.99      0.99      0.99       519

**Running Gradient Boosting classifier**

In [52]:
from sklearn.ensemble import GradientBoostingClassifier

In [53]:
#predicting using the Gradient_Boosting_Classifier
model_GradientBoosting = GradientBoostingClassifier(n_estimators=150,
                                                     random_state=10)

#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,y_train)

y_pred=model_GradientBoosting.predict(X_test)

In [54]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[101   1   0   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]

---------Accuracy Score------------
0.9980732177263969

---------Classification Report------------
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

    accuracy                           1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519

# Catboost

In [ ]:
# pip install catboost

In [55]:
from catboost import CatBoostClassifier

In [56]:
#predicting using the Gradient_Boosting_Classifier
model_GradientBoosting = CatBoostClassifier()

#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,y_train)

y_pred=model_GradientBoosting.predict(X_test)

Learning rate set to 0.079896
0:	learn: 1.2681340	total: 150ms	remaining: 2m 29s
1:	learn: 1.1800890	total: 151ms	remaining: 1m 15s
2:	learn: 1.0905759	total: 151ms	remaining: 50.3s
3:	learn: 1.0106046	total: 152ms	remaining: 37.9s
4:	learn: 0.9450573	total: 153ms	remaining: 30.4s
5:	learn: 0.8966915	total: 154ms	remaining: 25.5s
6:	learn: 0.8501689	total: 156ms	remaining: 22.1s
7:	learn: 0.7972903	total: 158ms	remaining: 19.6s
8:	learn: 0.7614882	total: 159ms	remaining: 17.5s
9:	learn: 0.7260354	total: 160ms	remaining: 15.8s
10:	learn: 0.6962340	total: 161ms	remaining: 14.4s
11:	learn: 0.6669178	total: 161ms	remaining: 13.3s
12:	learn: 0.6322237	total: 162ms	remaining: 12.3s
13:	learn: 0.6083418	total: 163ms	remaining: 11.5s
14:	learn: 0.5857253	total: 164ms	remaining: 10.8s
15:	learn: 0.5625754	total: 165ms	remaining: 10.2s
16:	learn: 0.5393360	total: 166ms	remaining: 9.61s
17:	learn: 0.5193320	total: 167ms	remaining: 9.12s
18:	learn: 0.5045812	total: 168ms	remaining: 8.67s
19:	learn: 0.4924007	total: 168ms	remaining: 8.25s
20:	learn: 0.4784799	total: 169ms	remaining: 7.89s
21:	learn: 0.4680009	total: 170ms	remaining: 7.56s
22:	learn: 0.4560900	total: 171ms	remaining: 7.26s
23:	learn: 0.4378798	total: 172ms	remaining: 6.99s
24:	learn: 0.4274538	total: 173ms	remaining: 6.75s
25:	learn: 0.4153746	total: 174ms	remaining: 6.51s
26:	learn: 0.4004089	total: 175ms	remaining: 6.3s
27:	learn: 0.3913983	total: 176ms	remaining: 6.11s
28:	learn: 0.3791005	total: 177ms	remaining: 5.93s
29:	learn: 0.3704285	total: 178ms	remaining: 5.75s
30:	learn: 0.3596671	total: 179ms	remaining: 5.58s
31:	learn: 0.3532758	total: 179ms	remaining: 5.42s
32:	learn: 0.3424245	total: 180ms	remaining: 5.28s
33:	learn: 0.3356953	total: 181ms	remaining: 5.13s
34:	learn: 0.3273423	total: 182ms	remaining: 5.01s
35:	learn: 0.3179370	total: 183ms	remaining: 4.89s
36:	learn: 0.3109379	total: 184ms	remaining: 4.78s
37:	learn: 0.3049418	total: 184ms	remaining: 4.67s
38:	learn: 0.2984823	total: 185ms	remaining: 4.56s
39:	learn: 0.2914912	total: 186ms	remaining: 4.46s
40:	learn: 0.2862816	total: 187ms	remaining: 4.37s
41:	learn: 0.2818845	total: 188ms	remaining: 4.28s
42:	learn: 0.2767727	total: 188ms	remaining: 4.19s
43:	learn: 0.2732620	total: 189ms	remaining: 4.11s
44:	learn: 0.2692247	total: 190ms	remaining: 4.04s
45:	learn: 0.2626803	total: 192ms	remaining: 3.99s
46:	learn: 0.2591385	total: 194ms	remaining: 3.93s
47:	learn: 0.2532294	total: 195ms	remaining: 3.87s
48:	learn: 0.2496632	total: 196ms	remaining: 3.81s
49:	learn: 0.2451430	total: 197ms	remaining: 3.74s
50:	learn: 0.2413553	total: 198ms	remaining: 3.68s
51:	learn: 0.2369410	total: 199ms	remaining: 3.63s
52:	learn: 0.2329248	total: 200ms	remaining: 3.57s
53:	learn: 0.2302764	total: 201ms	remaining: 3.53s
54:	learn: 0.2265154	total: 203ms	remaining: 3.48s
55:	learn: 0.2218604	total: 204ms	remaining: 3.43s
56:	learn: 0.2187394	total: 205ms	remaining: 3.39s
57:	learn: 0.2149991	total: 206ms	remaining: 3.35s
58:	learn: 0.2121850	total: 208ms	remaining: 3.31s
59:	learn: 0.2092247	total: 209ms	remaining: 3.27s
60:	learn: 0.2066433	total: 209ms	remaining: 3.22s
61:	learn: 0.2024685	total: 210ms	remaining: 3.18s
62:	learn: 0.2002673	total: 211ms	remaining: 3.14s
63:	learn: 0.1991622	total: 211ms	remaining: 3.09s
64:	learn: 0.1965388	total: 212ms	remaining: 3.05s
65:	learn: 0.1930715	total: 213ms	remaining: 3.02s
66:	learn: 0.1905236	total: 214ms	remaining: 2.98s
67:	learn: 0.1888703	total: 215ms	remaining: 2.94s
68:	learn: 0.1873513	total: 216ms	remaining: 2.92s
69:	learn: 0.1855856	total: 218ms	remaining: 2.89s
70:	learn: 0.1829848	total: 219ms	remaining: 2.86s
71:	learn: 0.1815483	total: 220ms	remaining: 2.83s
72:	learn: 0.1797310	total: 221ms	remaining: 2.81s
73:	learn: 0.1780523	total: 222ms	remaining: 2.78s
74:	learn: 0.1748336	total: 223ms	remaining: 2.75s
75:	learn: 0.1724970	total: 224ms	remaining: 2.72s
76:	learn: 0.1698374	total: 224ms	remaining: 2.69s
77:	learn: 0.1686212	total: 225ms	remaining: 2.66s
78:	learn: 0.1669189	total: 226ms	remaining: 2.64s
79:	learn: 0.1638592	total: 227ms	remaining: 2.61s
80:	learn: 0.1619907	total: 228ms	remaining: 2.58s
81:	learn: 0.1603994	total: 229ms	remaining: 2.56s
82:	learn: 0.1590722	total: 230ms	remaining: 2.54s
83:	learn: 0.1565778	total: 231ms	remaining: 2.52s
84:	learn: 0.1549209	total: 232ms	remaining: 2.5s
85:	learn: 0.1526773	total: 233ms	remaining: 2.48s
86:	learn: 0.1513942	total: 234ms	remaining: 2.45s
87:	learn: 0.1492391	total: 235ms	remaining: 2.43s
88:	learn: 0.1477229	total: 236ms	remaining: 2.41s
89:	learn: 0.1457067	total: 236ms	remaining: 2.39s
90:	learn: 0.1448011	total: 237ms	remaining: 2.37s
91:	learn: 0.1435286	total: 238ms	remaining: 2.35s
92:	learn: 0.1424431	total: 239ms	remaining: 2.33s
93:	learn: 0.1409403	total: 240ms	remaining: 2.31s
94:	learn: 0.1396260	total: 240ms	remaining: 2.29s
95:	learn: 0.1386471	total: 241ms	remaining: 2.27s
96:	learn: 0.1370703	total: 242ms	remaining: 2.25s
97:	learn: 0.1360613	total: 243ms	remaining: 2.23s
98:	learn: 0.1344784	total: 244ms	remaining: 2.22s
99:	learn: 0.1327996	total: 245ms	remaining: 2.2s
100:	learn: 0.1312091	total: 246ms	remaining: 2.19s
101:	learn: 0.1300623	total: 246ms	remaining: 2.17s
102:	learn: 0.1290266	total: 247ms	remaining: 2.15s
103:	learn: 0.1278776	total: 248ms	remaining: 2.14s
104:	learn: 0.1268792	total: 249ms	remaining: 2.12s
105:	learn: 0.1259749	total: 249ms	remaining: 2.1s
106:	learn: 0.1250733	total: 250ms	remaining: 2.09s
107:	learn: 0.1241519	total: 251ms	remaining: 2.07s
108:	learn: 0.1233099	total: 252ms	remaining: 2.06s
109:	learn: 0.1225955	total: 253ms	remaining: 2.04s
110:	learn: 0.1216275	total: 253ms	remaining: 2.03s
111:	learn: 0.1205214	total: 254ms	remaining: 2.02s
112:	learn: 0.1189992	total: 255ms	remaining: 2s
113:	learn: 0.1180037	total: 256ms	remaining: 1.99s
114:	learn: 0.1172663	total: 256ms	remaining: 1.97s
115:	learn: 0.1160430	total: 257ms	remaining: 1.96s
116:	learn: 0.1152940	total: 258ms	remaining: 1.95s
117:	learn: 0.1143726	total: 259ms	remaining: 1.93s
118:	learn: 0.1132996	total: 260ms	remaining: 1.92s
119:	learn: 0.1124024	total: 261ms	remaining: 1.91s
120:	learn: 0.1115514	total: 262ms	remaining: 1.91s
121:	learn: 0.1102529	total: 263ms	remaining: 1.9s
122:	learn: 0.1089904	total: 265ms	remaining: 1.89s
123:	learn: 0.1083970	total: 266ms	remaining: 1.88s
124:	learn: 0.1074747	total: 267ms	remaining: 1.87s
125:	learn: 0.1066660	total: 268ms	remaining: 1.86s
126:	learn: 0.1055131	total: 269ms	remaining: 1.85s
127:	learn: 0.1047252	total: 270ms	remaining: 1.84s
128:	learn: 0.1035118	total: 271ms	remaining: 1.83s
129:	learn: 0.1027902	total: 272ms	remaining: 1.82s
130:	learn: 0.1021532	total: 273ms	remaining: 1.81s
131:	learn: 0.1012304	total: 274ms	remaining: 1.8s
132:	learn: 0.1004132	total: 275ms	remaining: 1.79s
133:	learn: 0.0993949	total: 276ms	remaining: 1.78s
134:	learn: 0.0983483	total: 277ms	remaining: 1.77s
135:	learn: 0.0976871	total: 277ms	remaining: 1.76s
136:	learn: 0.0965189	total: 278ms	remaining: 1.75s
137:	learn: 0.0955684	total: 279ms	remaining: 1.74s
138:	learn: 0.0950492	total: 280ms	remaining: 1.73s
139:	learn: 0.0941236	total: 280ms	remaining: 1.72s
140:	learn: 0.0933803	total: 281ms	remaining: 1.71s
141:	learn: 0.0927016	total: 282ms	remaining: 1.7s
142:	learn: 0.0918626	total: 282ms	remaining: 1.69s
143:	learn: 0.0913990	total: 283ms	remaining: 1.68s
144:	learn: 0.0905789	total: 284ms	remaining: 1.68s
145:	learn: 0.0901490	total: 285ms	remaining: 1.67s
146:	learn: 0.0895287	total: 286ms	remaining: 1.66s
147:	learn: 0.0890280	total: 286ms	remaining: 1.65s
148:	learn: 0.0885538	total: 287ms	remaining: 1.64s
149:	learn: 0.0880301	total: 288ms	remaining: 1.63s
150:	learn: 0.0876095	total: 289ms	remaining: 1.63s
151:	learn: 0.0872497	total: 290ms	remaining: 1.62s
152:	learn: 0.0868188	total: 292ms	remaining: 1.62s
153:	learn: 0.0863744	total: 293ms	remaining: 1.61s
154:	learn: 0.0860132	total: 294ms	remaining: 1.6s
155:	learn: 0.0853572	total: 296ms	remaining: 1.6s
156:	learn: 0.0847374	total: 297ms	remaining: 1.59s
157:	learn: 0.0840038	total: 298ms	remaining: 1.59s
158:	learn: 0.0834325	total: 299ms	remaining: 1.58s
159:	learn: 0.0828911	total: 300ms	remaining: 1.57s
160:	learn: 0.0821615	total: 301ms	remaining: 1.57s
161:	learn: 0.0818625	total: 302ms	remaining: 1.56s
162:	learn: 0.0811067	total: 303ms	remaining: 1.55s
163:	learn: 0.0807370	total: 303ms	remaining: 1.55s
164:	learn: 0.0802539	total: 304ms	remaining: 1.54s
165:	learn: 0.0799153	total: 305ms	remaining: 1.53s
166:	learn: 0.0791556	total: 306ms	remaining: 1.53s
167:	learn: 0.0786565	total: 307ms	remaining: 1.52s
168:	learn: 0.0780930	total: 308ms	remaining: 1.51s
169:	learn: 0.0775782	total: 309ms	remaining: 1.51s
170:	learn: 0.0770661	total: 310ms	remaining: 1.5s
171:	learn: 0.0766448	total: 311ms	remaining: 1.5s
172:	learn: 0.0758832	total: 312ms	remaining: 1.49s
173:	learn: 0.0755889	total: 312ms	remaining: 1.48s
174:	learn: 0.0749959	total: 313ms	remaining: 1.48s
175:	learn: 0.0745167	total: 314ms	remaining: 1.47s
176:	learn: 0.0740597	total: 315ms	remaining: 1.46s
177:	learn: 0.0735575	total: 316ms	remaining: 1.46s
178:	learn: 0.0732541	total: 317ms	remaining: 1.45s
179:	learn: 0.0727316	total: 318ms	remaining: 1.45s
180:	learn: 0.0722160	total: 319ms	remaining: 1.44s
181:	learn: 0.0719296	total: 320ms	remaining: 1.44s
182:	learn: 0.0713939	total: 320ms	remaining: 1.43s
183:	learn: 0.0708763	total: 321ms	remaining: 1.42s
184:	learn: 0.0703867	total: 322ms	remaining: 1.42s
185:	learn: 0.0697682	total: 323ms	remaining: 1.41s
186:	learn: 0.0694553	total: 324ms	remaining: 1.41s
187:	learn: 0.0692042	total: 325ms	remaining: 1.4s
188:	learn: 0.0686248	total: 326ms	remaining: 1.4s
189:	learn: 0.0682531	total: 327ms	remaining: 1.39s
190:	learn: 0.0678206	total: 328ms	remaining: 1.39s
191:	learn: 0.0675860	total: 328ms	remaining: 1.38s
192:	learn: 0.0671742	total: 329ms	remaining: 1.38s
193:	learn: 0.0667826	total: 330ms	remaining: 1.37s
194:	learn: 0.0665040	total: 331ms	remaining: 1.37s
195:	learn: 0.0661684	total: 332ms	remaining: 1.36s
196:	learn: 0.0657871	total: 333ms	remaining: 1.36s
197:	learn: 0.0654643	total: 335ms	remaining: 1.36s
198:	learn: 0.0651477	total: 336ms	remaining: 1.35s
199:	learn: 0.0648051	total: 337ms	remaining: 1.35s
200:	learn: 0.0643999	total: 338ms	remaining: 1.34s
201:	learn: 0.0641352	total: 339ms	remaining: 1.34s
202:	learn: 0.0637953	total: 339ms	remaining: 1.33s
203:	learn: 0.0634752	total: 340ms	remaining: 1.33s
204:	learn: 0.0631534	total: 341ms	remaining: 1.32s
205:	learn: 0.0628474	total: 342ms	remaining: 1.32s
206:	learn: 0.0624331	total: 343ms	remaining: 1.31s
207:	learn: 0.0621016	total: 344ms	remaining: 1.31s
208:	learn: 0.0618371	total: 345ms	remaining: 1.3s
209:	learn: 0.0615114	total: 346ms	remaining: 1.3s
210:	learn: 0.0612731	total: 347ms	remaining: 1.3s
211:	learn: 0.0608937	total: 348ms	remaining: 1.29s
212:	learn: 0.0606373	total: 348ms	remaining: 1.29s
213:	learn: 0.0604097	total: 349ms	remaining: 1.28s
214:	learn: 0.0598798	total: 350ms	remaining: 1.28s
215:	learn: 0.0596617	total: 351ms	remaining: 1.27s
216:	learn: 0.0592958	total: 352ms	remaining: 1.27s
217:	learn: 0.0590849	total: 353ms	remaining: 1.27s
218:	learn: 0.0588697	total: 354ms	remaining: 1.26s
219:	learn: 0.0585714	total: 355ms	remaining: 1.26s
220:	learn: 0.0583499	total: 356ms	remaining: 1.25s
221:	learn: 0.0580975	total: 357ms	remaining: 1.25s
222:	learn: 0.0577602	total: 358ms	remaining: 1.25s
223:	learn: 0.0574682	total: 359ms	remaining: 1.24s
224:	learn: 0.0572163	total: 360ms	remaining: 1.24s
225:	learn: 0.0569341	total: 362ms	remaining: 1.24s
226:	learn: 0.0567113	total: 363ms	remaining: 1.24s
227:	learn: 0.0564015	total: 364ms	remaining: 1.23s
228:	learn: 0.0561589	total: 365ms	remaining: 1.23s
229:	learn: 0.0558349	total: 366ms	remaining: 1.23s
230:	learn: 0.0555937	total: 367ms	remaining: 1.22s
231:	learn: 0.0553640	total: 368ms	remaining: 1.22s
232:	learn: 0.0550563	total: 369ms	remaining: 1.22s
233:	learn: 0.0546957	total: 370ms	remaining: 1.21s
234:	learn: 0.0545097	total: 371ms	remaining: 1.21s

235:	learn: 0.0541549	total: 372ms	remaining: 1.21s
236:	learn: 0.0538485	total: 373ms	remaining: 1.2s
237:	learn: 0.0534852	total: 374ms	remaining: 1.2s
238:	learn: 0.0533093	total: 375ms	remaining: 1.19s
239:	learn: 0.0529996	total: 376ms	remaining: 1.19s
240:	learn: 0.0527068	total: 377ms	remaining: 1.19s
241:	learn: 0.0525554	total: 378ms	remaining: 1.18s
242:	learn: 0.0524041	total: 379ms	remaining: 1.18s
243:	learn: 0.0521992	total: 380ms	remaining: 1.18s
244:	learn: 0.0518007	total: 381ms	remaining: 1.17s
245:	learn: 0.0516320	total: 382ms	remaining: 1.17s
246:	learn: 0.0513362	total: 383ms	remaining: 1.17s
247:	learn: 0.0510797	total: 385ms	remaining: 1.17s
248:	learn: 0.0509277	total: 386ms	remaining: 1.16s
249:	learn: 0.0507731	total: 387ms	remaining: 1.16s
250:	learn: 0.0504726	total: 388ms	remaining: 1.16s
251:	learn: 0.0502573	total: 389ms	remaining: 1.16s
252:	learn: 0.0500536	total: 390ms	remaining: 1.15s
253:	learn: 0.0496723	total: 391ms	remaining: 1.15s
254:	learn: 0.0494905	total: 392ms	remaining: 1.14s
255:	learn: 0.0492811	total: 393ms	remaining: 1.14s
256:	learn: 0.0491538	total: 394ms	remaining: 1.14s
257:	learn: 0.0490363	total: 395ms	remaining: 1.14s
258:	learn: 0.0486775	total: 396ms	remaining: 1.13s
259:	learn: 0.0485076	total: 397ms	remaining: 1.13s
260:	learn: 0.0482902	total: 398ms	remaining: 1.13s
261:	learn: 0.0481534	total: 399ms	remaining: 1.12s
262:	learn: 0.0478680	total: 400ms	remaining: 1.12s
263:	learn: 0.0475440	total: 401ms	remaining: 1.12s
264:	learn: 0.0473454	total: 402ms	remaining: 1.11s
265:	learn: 0.0470977	total: 404ms	remaining: 1.11s
266:	learn: 0.0469184	total: 405ms	remaining: 1.11s
267:	learn: 0.0465981	total: 406ms	remaining: 1.11s
268:	learn: 0.0464271	total: 407ms	remaining: 1.11s
269:	learn: 0.0462244	total: 408ms	remaining: 1.1s
270:	learn: 0.0461088	total: 410ms	remaining: 1.1s
271:	learn: 0.0458911	total: 411ms	remaining: 1.1s
272:	learn: 0.0457334	total: 412ms	remaining: 1.1s
273:	learn: 0.0456016	total: 413ms	remaining: 1.09s
274:	learn: 0.0453648	total: 414ms	remaining: 1.09s
275:	learn: 0.0451806	total: 415ms	remaining: 1.09s
276:	learn: 0.0450205	total: 416ms	remaining: 1.09s
277:	learn: 0.0448259	total: 417ms	remaining: 1.08s
278:	learn: 0.0446403	total: 418ms	remaining: 1.08s
279:	learn: 0.0444824	total: 419ms	remaining: 1.08s
280:	learn: 0.0443858	total: 420ms	remaining: 1.07s
281:	learn: 0.0442355	total: 421ms	remaining: 1.07s
282:	learn: 0.0441016	total: 422ms	remaining: 1.07s
283:	learn: 0.0438709	total: 423ms	remaining: 1.07s
284:	learn: 0.0437267	total: 424ms	remaining: 1.06s
285:	learn: 0.0434325	total: 425ms	remaining: 1.06s
286:	learn: 0.0432059	total: 426ms	remaining: 1.06s
287:	learn: 0.0430151	total: 427ms	remaining: 1.06s
288:	learn: 0.0428672	total: 428ms	remaining: 1.05s
289:	learn: 0.0426902	total: 429ms	remaining: 1.05s
290:	learn: 0.0425078	total: 430ms	remaining: 1.05s
291:	learn: 0.0423492	total: 431ms	remaining: 1.04s
292:	learn: 0.0422669	total: 432ms	remaining: 1.04s
293:	learn: 0.0420540	total: 433ms	remaining: 1.04s
294:	learn: 0.0418227	total: 434ms	remaining: 1.04s
295:	learn: 0.0416333	total: 435ms	remaining: 1.03s
296:	learn: 0.0415049	total: 436ms	remaining: 1.03s
297:	learn: 0.0414298	total: 437ms	remaining: 1.03s
298:	learn: 0.0413016	total: 438ms	remaining: 1.03s
299:	learn: 0.0412111	total: 439ms	remaining: 1.02s
300:	learn: 0.0410437	total: 440ms	remaining: 1.02s
301:	learn: 0.0407668	total: 441ms	remaining: 1.02s
302:	learn: 0.0405367	total: 442ms	remaining: 1.02s
303:	learn: 0.0403804	total: 443ms	remaining: 1.01s
304:	learn: 0.0402779	total: 444ms	remaining: 1.01s
305:	learn: 0.0401542	total: 445ms	remaining: 1.01s
306:	learn: 0.0400666	total: 447ms	remaining: 1.01s
307:	learn: 0.0399829	total: 448ms	remaining: 1s
308:	learn: 0.0398093	total: 449ms	remaining: 1s
309:	learn: 0.0396210	total: 450ms	remaining: 1s
310:	learn: 0.0395170	total: 451ms	remaining: 999ms
311:	learn: 0.0393170	total: 452ms	remaining: 997ms
312:	learn: 0.0392195	total: 453ms	remaining: 995ms
313:	learn: 0.0390889	total: 454ms	remaining: 993ms
314:	learn: 0.0388360	total: 455ms	remaining: 990ms
315:	learn: 0.0385926	total: 456ms	remaining: 988ms
316:	learn: 0.0384207	total: 457ms	remaining: 985ms
317:	learn: 0.0383281	total: 458ms	remaining: 983ms
318:	learn: 0.0382483	total: 459ms	remaining: 981ms
319:	learn: 0.0381626	total: 460ms	remaining: 978ms
320:	learn: 0.0380608	total: 461ms	remaining: 976ms
321:	learn: 0.0378909	total: 462ms	remaining: 973ms
322:	learn: 0.0377192	total: 463ms	remaining: 971ms
323:	learn: 0.0376124	total: 464ms	remaining: 968ms
324:	learn: 0.0374833	total: 465ms	remaining: 965ms
325:	learn: 0.0372563	total: 466ms	remaining: 963ms
326:	learn: 0.0371607	total: 467ms	remaining: 960ms
327:	learn: 0.0370426	total: 467ms	remaining: 958ms
328:	learn: 0.0369178	total: 468ms	remaining: 955ms
329:	learn: 0.0367611	total: 469ms	remaining: 953ms
330:	learn: 0.0366052	total: 470ms	remaining: 951ms
331:	learn: 0.0365225	total: 472ms	remaining: 949ms
332:	learn: 0.0363879	total: 473ms	remaining: 948ms
333:	learn: 0.0362840	total: 475ms	remaining: 946ms
334:	learn: 0.0361378	total: 476ms	remaining: 945ms
335:	learn: 0.0359761	total: 478ms	remaining: 944ms
336:	learn: 0.0358889	total: 480ms	remaining: 944ms
337:	learn: 0.0356747	total: 481ms	remaining: 942ms
338:	learn: 0.0355959	total: 482ms	remaining: 940ms
339:	learn: 0.0354912	total: 483ms	remaining: 938ms
340:	learn: 0.0353397	total: 485ms	remaining: 937ms
341:	learn: 0.0351883	total: 486ms	remaining: 935ms
342:	learn: 0.0350495	total: 487ms	remaining: 933ms
343:	learn: 0.0349429	total: 488ms	remaining: 931ms
344:	learn: 0.0348498	total: 489ms	remaining: 929ms
345:	learn: 0.0347808	total: 490ms	remaining: 927ms
346:	learn: 0.0346711	total: 491ms	remaining: 924ms
347:	learn: 0.0345677	total: 492ms	remaining: 922ms
348:	learn: 0.0344549	total: 493ms	remaining: 920ms
349:	learn: 0.0343655	total: 494ms	remaining: 917ms
350:	learn: 0.0342599	total: 495ms	remaining: 915ms
351:	learn: 0.0341442	total: 496ms	remaining: 913ms
352:	learn: 0.0340780	total: 497ms	remaining: 910ms
353:	learn: 0.0339904	total: 498ms	remaining: 908ms
354:	learn: 0.0338449	total: 499ms	remaining: 907ms
355:	learn: 0.0336893	total: 500ms	remaining: 905ms
356:	learn: 0.0336340	total: 501ms	remaining: 902ms
357:	learn: 0.0334859	total: 502ms	remaining: 900ms
358:	learn: 0.0334288	total: 503ms	remaining: 897ms
359:	learn: 0.0332468	total: 503ms	remaining: 895ms
360:	learn: 0.0331933	total: 504ms	remaining: 893ms
361:	learn: 0.0330582	total: 505ms	remaining: 891ms
362:	learn: 0.0329266	total: 506ms	remaining: 889ms
363:	learn: 0.0328104	total: 507ms	remaining: 886ms
364:	learn: 0.0326982	total: 508ms	remaining: 884ms
365:	learn: 0.0325715	total: 509ms	remaining: 882ms
366:	learn: 0.0324363	total: 510ms	remaining: 879ms
367:	learn: 0.0323169	total: 511ms	remaining: 877ms
368:	learn: 0.0321921	total: 511ms	remaining: 875ms
369:	learn: 0.0321181	total: 512ms	remaining: 872ms
370:	learn: 0.0320528	total: 513ms	remaining: 870ms
371:	learn: 0.0319379	total: 514ms	remaining: 868ms
372:	learn: 0.0318444	total: 515ms	remaining: 866ms
373:	learn: 0.0317231	total: 517ms	remaining: 865ms
374:	learn: 0.0315926	total: 518ms	remaining: 863ms
375:	learn: 0.0315199	total: 519ms	remaining: 862ms
376:	learn: 0.0314291	total: 520ms	remaining: 859ms
377:	learn: 0.0313356	total: 521ms	remaining: 857ms
378:	learn: 0.0312478	total: 522ms	remaining: 856ms
379:	learn: 0.0311659	total: 523ms	remaining: 854ms
380:	learn: 0.0310613	total: 524ms	remaining: 852ms
381:	learn: 0.0310052	total: 525ms	remaining: 850ms
382:	learn: 0.0309289	total: 526ms	remaining: 847ms
383:	learn: 0.0307808	total: 527ms	remaining: 845ms
384:	learn: 0.0306672	total: 528ms	remaining: 843ms
385:	learn: 0.0305874	total: 529ms	remaining: 841ms
386:	learn: 0.0305212	total: 530ms	remaining: 839ms
387:	learn: 0.0304129	total: 531ms	remaining: 837ms
388:	learn: 0.0303665	total: 532ms	remaining: 835ms
389:	learn: 0.0302749	total: 533ms	remaining: 834ms
390:	learn: 0.0302129	total: 534ms	remaining: 831ms
391:	learn: 0.0301298	total: 535ms	remaining: 829ms
392:	learn: 0.0300752	total: 536ms	remaining: 827ms
393:	learn: 0.0300121	total: 536ms	remaining: 825ms
394:	learn: 0.0299251	total: 537ms	remaining: 823ms
395:	learn: 0.0298287	total: 538ms	remaining: 821ms
396:	learn: 0.0297399	total: 539ms	remaining: 819ms
397:	learn: 0.0296404	total: 540ms	remaining: 816ms
398:	learn: 0.0295845	total: 541ms	remaining: 814ms
399:	learn: 0.0294639	total: 542ms	remaining: 813ms
400:	learn: 0.0293627	total: 543ms	remaining: 811ms
401:	learn: 0.0292589	total: 544ms	remaining: 809ms
402:	learn: 0.0292006	total: 545ms	remaining: 808ms
403:	learn: 0.0291371	total: 547ms	remaining: 806ms
404:	learn: 0.0290755	total: 547ms	remaining: 804ms
405:	learn: 0.0290228	total: 548ms	remaining: 802ms
406:	learn: 0.0289264	total: 549ms	remaining: 800ms
407:	learn: 0.0288183	total: 550ms	remaining: 799ms
408:	learn: 0.0287144	total: 551ms	remaining: 797ms
409:	learn: 0.0286495	total: 552ms	remaining: 795ms
410:	learn: 0.0284944	total: 554ms	remaining: 793ms

411:	learn: 0.0283771	total: 555ms	remaining: 793ms
412:	learn: 0.0282422	total: 556ms	remaining: 791ms
413:	learn: 0.0282055	total: 557ms	remaining: 789ms
414:	learn: 0.0281554	total: 559ms	remaining: 787ms
415:	learn: 0.0280134	total: 560ms	remaining: 786ms
416:	learn: 0.0279312	total: 561ms	remaining: 784ms
417:	learn: 0.0278061	total: 561ms	remaining: 782ms
418:	learn: 0.0277617	total: 562ms	remaining: 780ms
419:	learn: 0.0276749	total: 563ms	remaining: 778ms
420:	learn: 0.0276340	total: 564ms	remaining: 776ms
421:	learn: 0.0275709	total: 565ms	remaining: 774ms
422:	learn: 0.0274243	total: 566ms	remaining: 772ms
423:	learn: 0.0273240	total: 567ms	remaining: 770ms
424:	learn: 0.0272474	total: 568ms	remaining: 769ms
425:	learn: 0.0271921	total: 569ms	remaining: 767ms
426:	learn: 0.0270984	total: 570ms	remaining: 765ms
427:	learn: 0.0270121	total: 571ms	remaining: 763ms
428:	learn: 0.0269368	total: 572ms	remaining: 761ms
429:	learn: 0.0268862	total: 573ms	remaining: 759ms
430:	learn: 0.0268199	total: 574ms	remaining: 757ms
431:	learn: 0.0267848	total: 575ms	remaining: 755ms
432:	learn: 0.0267290	total: 575ms	remaining: 754ms
433:	learn: 0.0266678	total: 577ms	remaining: 752ms
434:	learn: 0.0265699	total: 578ms	remaining: 750ms
435:	learn: 0.0264694	total: 579ms	remaining: 748ms
436:	learn: 0.0263777	total: 580ms	remaining: 747ms
437:	learn: 0.0263062	total: 580ms	remaining: 745ms
438:	learn: 0.0262419	total: 581ms	remaining: 743ms
439:	learn: 0.0261803	total: 582ms	remaining: 741ms
440:	learn: 0.0261117	total: 584ms	remaining: 740ms
441:	learn: 0.0260273	total: 584ms	remaining: 738ms
442:	learn: 0.0259650	total: 586ms	remaining: 737ms
443:	learn: 0.0258725	total: 587ms	remaining: 735ms
444:	learn: 0.0258005	total: 588ms	remaining: 734ms
445:	learn: 0.0257553	total: 589ms	remaining: 732ms
446:	learn: 0.0256664	total: 590ms	remaining: 730ms
447:	learn: 0.0255806	total: 591ms	remaining: 728ms
448:	learn: 0.0255389	total: 592ms	remaining: 727ms
449:	learn: 0.0254909	total: 593ms	remaining: 725ms
450:	learn: 0.0254262	total: 594ms	remaining: 723ms
451:	learn: 0.0253716	total: 595ms	remaining: 721ms
452:	learn: 0.0252633	total: 596ms	remaining: 720ms
453:	learn: 0.0251851	total: 597ms	remaining: 718ms
454:	learn: 0.0251001	total: 598ms	remaining: 716ms
455:	learn: 0.0250479	total: 599ms	remaining: 714ms
456:	learn: 0.0250097	total: 600ms	remaining: 713ms
457:	learn: 0.0249292	total: 601ms	remaining: 711ms
458:	learn: 0.0248163	total: 601ms	remaining: 709ms
459:	learn: 0.0247508	total: 602ms	remaining: 707ms
460:	learn: 0.0247029	total: 603ms	remaining: 706ms
461:	learn: 0.0246672	total: 604ms	remaining: 704ms
462:	learn: 0.0246086	total: 605ms	remaining: 702ms
463:	learn: 0.0245616	total: 606ms	remaining: 700ms
464:	learn: 0.0244828	total: 607ms	remaining: 699ms
465:	learn: 0.0244322	total: 608ms	remaining: 697ms
466:	learn: 0.0243644	total: 609ms	remaining: 695ms
467:	learn: 0.0242838	total: 610ms	remaining: 693ms
468:	learn: 0.0242238	total: 611ms	remaining: 692ms
469:	learn: 0.0241739	total: 612ms	remaining: 690ms
470:	learn: 0.0241253	total: 614ms	remaining: 689ms
471:	learn: 0.0240618	total: 615ms	remaining: 688ms
472:	learn: 0.0240175	total: 618ms	remaining: 688ms
473:	learn: 0.0239324	total: 619ms	remaining: 687ms
474:	learn: 0.0238930	total: 620ms	remaining: 686ms
475:	learn: 0.0238603	total: 622ms	remaining: 684ms
476:	learn: 0.0238312	total: 623ms	remaining: 683ms
477:	learn: 0.0237888	total: 624ms	remaining: 681ms
478:	learn: 0.0237046	total: 625ms	remaining: 680ms
479:	learn: 0.0236231	total: 626ms	remaining: 678ms
480:	learn: 0.0235540	total: 627ms	remaining: 676ms
481:	learn: 0.0235073	total: 628ms	remaining: 675ms
482:	learn: 0.0234765	total: 629ms	remaining: 673ms
483:	learn: 0.0234274	total: 630ms	remaining: 672ms
484:	learn: 0.0233586	total: 631ms	remaining: 670ms
485:	learn: 0.0233279	total: 632ms	remaining: 669ms
486:	learn: 0.0233009	total: 633ms	remaining: 667ms
487:	learn: 0.0232380	total: 634ms	remaining: 665ms
488:	learn: 0.0231696	total: 635ms	remaining: 664ms
489:	learn: 0.0230913	total: 636ms	remaining: 662ms
490:	learn: 0.0230468	total: 637ms	remaining: 660ms
491:	learn: 0.0230010	total: 638ms	remaining: 659ms
492:	learn: 0.0229411	total: 639ms	remaining: 657ms
493:	learn: 0.0228987	total: 640ms	remaining: 655ms
494:	learn: 0.0228347	total: 641ms	remaining: 654ms
495:	learn: 0.0227985	total: 642ms	remaining: 652ms
496:	learn: 0.0226901	total: 643ms	remaining: 651ms
497:	learn: 0.0226311	total: 644ms	remaining: 649ms
498:	learn: 0.0225608	total: 645ms	remaining: 647ms
499:	learn: 0.0225280	total: 646ms	remaining: 646ms
500:	learn: 0.0224881	total: 647ms	remaining: 644ms
501:	learn: 0.0224593	total: 648ms	remaining: 643ms
502:	learn: 0.0224304	total: 649ms	remaining: 641ms
503:	learn: 0.0223833	total: 650ms	remaining: 640ms
504:	learn: 0.0223235	total: 651ms	remaining: 638ms
505:	learn: 0.0222524	total: 652ms	remaining: 636ms
506:	learn: 0.0222139	total: 653ms	remaining: 635ms
507:	learn: 0.0221784	total: 654ms	remaining: 634ms
508:	learn: 0.0221420	total: 655ms	remaining: 632ms
509:	learn: 0.0221080	total: 656ms	remaining: 630ms
510:	learn: 0.0220618	total: 657ms	remaining: 629ms
511:	learn: 0.0219920	total: 658ms	remaining: 628ms
512:	learn: 0.0219691	total: 660ms	remaining: 627ms
513:	learn: 0.0219431	total: 661ms	remaining: 625ms
514:	learn: 0.0218789	total: 662ms	remaining: 624ms
515:	learn: 0.0218140	total: 663ms	remaining: 622ms
516:	learn: 0.0217686	total: 664ms	remaining: 621ms
517:	learn: 0.0217082	total: 665ms	remaining: 619ms
518:	learn: 0.0216768	total: 666ms	remaining: 617ms
519:	learn: 0.0216234	total: 667ms	remaining: 616ms
520:	learn: 0.0215567	total: 668ms	remaining: 614ms
521:	learn: 0.0214992	total: 669ms	remaining: 613ms
522:	learn: 0.0214153	total: 670ms	remaining: 611ms
523:	learn: 0.0213726	total: 671ms	remaining: 610ms
524:	learn: 0.0213096	total: 672ms	remaining: 608ms
525:	learn: 0.0212740	total: 673ms	remaining: 606ms
526:	learn: 0.0212335	total: 674ms	remaining: 605ms
527:	learn: 0.0211904	total: 675ms	remaining: 603ms
528:	learn: 0.0211510	total: 675ms	remaining: 601ms
529:	learn: 0.0211012	total: 676ms	remaining: 600ms
530:	learn: 0.0210721	total: 677ms	remaining: 598ms
531:	learn: 0.0210193	total: 678ms	remaining: 597ms
532:	learn: 0.0209858	total: 679ms	remaining: 595ms
533:	learn: 0.0209485	total: 680ms	remaining: 593ms
534:	learn: 0.0208905	total: 681ms	remaining: 592ms
535:	learn: 0.0208342	total: 682ms	remaining: 590ms
536:	learn: 0.0207825	total: 683ms	remaining: 589ms
537:	learn: 0.0207118	total: 684ms	remaining: 587ms
538:	learn: 0.0206587	total: 685ms	remaining: 586ms
539:	learn: 0.0206359	total: 686ms	remaining: 584ms
540:	learn: 0.0205984	total: 687ms	remaining: 583ms
541:	learn: 0.0205476	total: 688ms	remaining: 581ms
542:	learn: 0.0204867	total: 689ms	remaining: 580ms
543:	learn: 0.0204669	total: 690ms	remaining: 578ms
544:	learn: 0.0203955	total: 690ms	remaining: 576ms
545:	learn: 0.0203614	total: 691ms	remaining: 575ms
546:	learn: 0.0203206	total: 692ms	remaining: 573ms
547:	learn: 0.0202746	total: 693ms	remaining: 572ms
548:	learn: 0.0202406	total: 694ms	remaining: 570ms
549:	learn: 0.0201949	total: 695ms	remaining: 569ms
550:	learn: 0.0201731	total: 696ms	remaining: 567ms
551:	learn: 0.0201149	total: 697ms	remaining: 566ms
552:	learn: 0.0200902	total: 698ms	remaining: 564ms
553:	learn: 0.0200339	total: 699ms	remaining: 563ms
554:	learn: 0.0199807	total: 700ms	remaining: 562ms
555:	learn: 0.0199475	total: 701ms	remaining: 560ms
556:	learn: 0.0198997	total: 702ms	remaining: 558ms
557:	learn: 0.0198668	total: 703ms	remaining: 557ms
558:	learn: 0.0198158	total: 704ms	remaining: 555ms
559:	learn: 0.0197816	total: 705ms	remaining: 554ms
560:	learn: 0.0197377	total: 706ms	remaining: 552ms
561:	learn: 0.0196973	total: 706ms	remaining: 551ms
562:	learn: 0.0196767	total: 707ms	remaining: 549ms
563:	learn: 0.0196218	total: 708ms	remaining: 547ms
564:	learn: 0.0195880	total: 709ms	remaining: 546ms
565:	learn: 0.0195253	total: 710ms	remaining: 544ms
566:	learn: 0.0194958	total: 711ms	remaining: 543ms
567:	learn: 0.0194663	total: 712ms	remaining: 541ms
568:	learn: 0.0194382	total: 713ms	remaining: 540ms
569:	learn: 0.0194127	total: 713ms	remaining: 538ms
570:	learn: 0.0193877	total: 714ms	remaining: 537ms
571:	learn: 0.0193371	total: 715ms	remaining: 535ms
572:	learn: 0.0192812	total: 716ms	remaining: 533ms
573:	learn: 0.0192428	total: 717ms	remaining: 532ms
574:	learn: 0.0191949	total: 717ms	remaining: 530ms
575:	learn: 0.0191624	total: 718ms	remaining: 529ms
576:	learn: 0.0191091	total: 719ms	remaining: 527ms
577:	learn: 0.0190802	total: 720ms	remaining: 526ms
578:	learn: 0.0190258	total: 721ms	remaining: 524ms
579:	learn: 0.0189960	total: 722ms	remaining: 522ms
580:	learn: 0.0189708	total: 722ms	remaining: 521ms
581:	learn: 0.0189500	total: 723ms	remaining: 519ms
582:	learn: 0.0189041	total: 724ms	remaining: 518ms
583:	learn: 0.0188729	total: 725ms	remaining: 517ms
584:	learn: 0.0188508	total: 726ms	remaining: 515ms
585:	learn: 0.0188234	total: 727ms	remaining: 514ms
586:	learn: 0.0187957	total: 728ms	remaining: 512ms
587:	learn: 0.0187708	total: 729ms	remaining: 511ms
588:	learn: 0.0187345	total: 730ms	remaining: 509ms
589:	learn: 0.0187154	total: 730ms	remaining: 508ms
590:	learn: 0.0186396	total: 731ms	remaining: 506ms
591:	learn: 0.0186056	total: 732ms	remaining: 505ms
592:	learn: 0.0185572	total: 733ms	remaining: 503ms
593:	learn: 0.0185245	total: 734ms	remaining: 502ms
594:	learn: 0.0184886	total: 735ms	remaining: 500ms
595:	learn: 0.0184464	total: 736ms	remaining: 499ms
596:	learn: 0.0184171	total: 737ms	remaining: 497ms
597:	learn: 0.0183882	total: 737ms	remaining: 496ms
598:	learn: 0.0183168	total: 738ms	remaining: 494ms

599:	learn: 0.0182694	total: 740ms	remaining: 493ms
600:	learn: 0.0182232	total: 741ms	remaining: 492ms
601:	learn: 0.0181984	total: 742ms	remaining: 490ms
602:	learn: 0.0181650	total: 743ms	remaining: 489ms
603:	learn: 0.0181398	total: 744ms	remaining: 488ms
604:	learn: 0.0181111	total: 745ms	remaining: 486ms
605:	learn: 0.0180839	total: 746ms	remaining: 485ms
606:	learn: 0.0180654	total: 746ms	remaining: 483ms
607:	learn: 0.0180441	total: 747ms	remaining: 482ms
608:	learn: 0.0180084	total: 748ms	remaining: 480ms
609:	learn: 0.0179798	total: 749ms	remaining: 479ms
610:	learn: 0.0179150	total: 750ms	remaining: 478ms
611:	learn: 0.0178882	total: 751ms	remaining: 476ms
612:	learn: 0.0178717	total: 752ms	remaining: 475ms
613:	learn: 0.0178279	total: 753ms	remaining: 473ms
614:	learn: 0.0177852	total: 754ms	remaining: 472ms
615:	learn: 0.0177420	total: 755ms	remaining: 470ms
616:	learn: 0.0177003	total: 756ms	remaining: 469ms
617:	learn: 0.0176765	total: 756ms	remaining: 468ms
618:	learn: 0.0176336	total: 757ms	remaining: 466ms
619:	learn: 0.0175597	total: 759ms	remaining: 465ms
620:	learn: 0.0175289	total: 759ms	remaining: 463ms
621:	learn: 0.0175056	total: 760ms	remaining: 462ms
622:	learn: 0.0174658	total: 761ms	remaining: 461ms
623:	learn: 0.0174005	total: 762ms	remaining: 459ms
624:	learn: 0.0173782	total: 763ms	remaining: 458ms
625:	learn: 0.0173505	total: 764ms	remaining: 457ms
626:	learn: 0.0173110	total: 765ms	remaining: 455ms
627:	learn: 0.0172857	total: 766ms	remaining: 454ms
628:	learn: 0.0172543	total: 767ms	remaining: 452ms
629:	learn: 0.0172046	total: 768ms	remaining: 451ms
630:	learn: 0.0171853	total: 769ms	remaining: 450ms
631:	learn: 0.0171229	total: 770ms	remaining: 448ms
632:	learn: 0.0170911	total: 772ms	remaining: 447ms
633:	learn: 0.0170631	total: 773ms	remaining: 446ms
634:	learn: 0.0170388	total: 774ms	remaining: 445ms
635:	learn: 0.0170109	total: 775ms	remaining: 444ms
636:	learn: 0.0169868	total: 776ms	remaining: 442ms
637:	learn: 0.0169488	total: 777ms	remaining: 441ms
638:	learn: 0.0169243	total: 778ms	remaining: 440ms
639:	learn: 0.0169016	total: 779ms	remaining: 438ms
640:	learn: 0.0168419	total: 780ms	remaining: 437ms
641:	learn: 0.0168272	total: 781ms	remaining: 435ms
642:	learn: 0.0167965	total: 782ms	remaining: 434ms
643:	learn: 0.0167649	total: 783ms	remaining: 433ms
644:	learn: 0.0167331	total: 784ms	remaining: 431ms
645:	learn: 0.0166897	total: 785ms	remaining: 430ms
646:	learn: 0.0166558	total: 786ms	remaining: 429ms
647:	learn: 0.0166366	total: 787ms	remaining: 427ms
648:	learn: 0.0166011	total: 788ms	remaining: 426ms
649:	learn: 0.0165792	total: 789ms	remaining: 425ms
650:	learn: 0.0165650	total: 789ms	remaining: 423ms
651:	learn: 0.0165339	total: 790ms	remaining: 422ms
652:	learn: 0.0165175	total: 791ms	remaining: 420ms
653:	learn: 0.0164952	total: 792ms	remaining: 419ms
654:	learn: 0.0164779	total: 793ms	remaining: 418ms
655:	learn: 0.0164579	total: 794ms	remaining: 416ms
656:	learn: 0.0164400	total: 795ms	remaining: 415ms
657:	learn: 0.0164090	total: 796ms	remaining: 414ms
658:	learn: 0.0163858	total: 797ms	remaining: 413ms
659:	learn: 0.0163635	total: 798ms	remaining: 411ms
660:	learn: 0.0163158	total: 799ms	remaining: 410ms
661:	learn: 0.0162909	total: 800ms	remaining: 408ms
662:	learn: 0.0162720	total: 801ms	remaining: 407ms
663:	learn: 0.0162515	total: 802ms	remaining: 406ms
664:	learn: 0.0161929	total: 803ms	remaining: 405ms
665:	learn: 0.0161570	total: 805ms	remaining: 404ms
666:	learn: 0.0161350	total: 806ms	remaining: 402ms
667:	learn: 0.0161073	total: 807ms	remaining: 401ms
668:	learn: 0.0160881	total: 808ms	remaining: 400ms
669:	learn: 0.0160503	total: 809ms	remaining: 398ms
670:	learn: 0.0160357	total: 810ms	remaining: 397ms
671:	learn: 0.0160188	total: 811ms	remaining: 396ms
672:	learn: 0.0159789	total: 812ms	remaining: 394ms
673:	learn: 0.0159623	total: 812ms	remaining: 393ms
674:	learn: 0.0159367	total: 813ms	remaining: 392ms
675:	learn: 0.0159075	total: 814ms	remaining: 390ms
676:	learn: 0.0158823	total: 815ms	remaining: 389ms
677:	learn: 0.0158302	total: 816ms	remaining: 388ms
678:	learn: 0.0157966	total: 817ms	remaining: 386ms
679:	learn: 0.0157636	total: 818ms	remaining: 385ms
680:	learn: 0.0157246	total: 819ms	remaining: 384ms
681:	learn: 0.0157030	total: 820ms	remaining: 382ms
682:	learn: 0.0156596	total: 821ms	remaining: 381ms
683:	learn: 0.0156111	total: 822ms	remaining: 380ms
684:	learn: 0.0155927	total: 823ms	remaining: 378ms
685:	learn: 0.0155580	total: 824ms	remaining: 377ms
686:	learn: 0.0155368	total: 825ms	remaining: 376ms
687:	learn: 0.0155194	total: 826ms	remaining: 375ms
688:	learn: 0.0154842	total: 827ms	remaining: 373ms
689:	learn: 0.0154676	total: 828ms	remaining: 372ms
690:	learn: 0.0154492	total: 829ms	remaining: 371ms
691:	learn: 0.0154234	total: 829ms	remaining: 369ms
692:	learn: 0.0154088	total: 831ms	remaining: 368ms
693:	learn: 0.0153862	total: 832ms	remaining: 367ms
694:	learn: 0.0153654	total: 833ms	remaining: 365ms
695:	learn: 0.0153519	total: 833ms	remaining: 364ms
696:	learn: 0.0153213	total: 834ms	remaining: 363ms
697:	learn: 0.0152989	total: 835ms	remaining: 361ms
698:	learn: 0.0152653	total: 836ms	remaining: 360ms
699:	learn: 0.0152191	total: 837ms	remaining: 359ms
700:	learn: 0.0152018	total: 838ms	remaining: 357ms
701:	learn: 0.0151637	total: 839ms	remaining: 356ms
702:	learn: 0.0151453	total: 840ms	remaining: 355ms
703:	learn: 0.0151008	total: 842ms	remaining: 354ms
704:	learn: 0.0150854	total: 844ms	remaining: 353ms
705:	learn: 0.0150702	total: 845ms	remaining: 352ms
706:	learn: 0.0150456	total: 846ms	remaining: 350ms
707:	learn: 0.0150283	total: 847ms	remaining: 349ms
708:	learn: 0.0150110	total: 848ms	remaining: 348ms
709:	learn: 0.0149620	total: 849ms	remaining: 347ms
710:	learn: 0.0149177	total: 850ms	remaining: 346ms
711:	learn: 0.0148778	total: 851ms	remaining: 344ms
712:	learn: 0.0148417	total: 853ms	remaining: 343ms
713:	learn: 0.0148280	total: 855ms	remaining: 342ms
714:	learn: 0.0148037	total: 856ms	remaining: 341ms
715:	learn: 0.0147873	total: 858ms	remaining: 340ms
716:	learn: 0.0147639	total: 860ms	remaining: 339ms
717:	learn: 0.0147426	total: 861ms	remaining: 338ms
718:	learn: 0.0147218	total: 862ms	remaining: 337ms
719:	learn: 0.0147108	total: 863ms	remaining: 336ms
720:	learn: 0.0146764	total: 864ms	remaining: 334ms
721:	learn: 0.0146560	total: 866ms	remaining: 333ms
722:	learn: 0.0146392	total: 867ms	remaining: 332ms
723:	learn: 0.0146276	total: 869ms	remaining: 331ms
724:	learn: 0.0146125	total: 870ms	remaining: 330ms
725:	learn: 0.0146004	total: 872ms	remaining: 329ms
726:	learn: 0.0145840	total: 873ms	remaining: 328ms
727:	learn: 0.0145708	total: 874ms	remaining: 327ms
728:	learn: 0.0145555	total: 875ms	remaining: 325ms
729:	learn: 0.0145274	total: 876ms	remaining: 324ms
730:	learn: 0.0145094	total: 877ms	remaining: 323ms
731:	learn: 0.0144994	total: 878ms	remaining: 322ms
732:	learn: 0.0144689	total: 880ms	remaining: 320ms
733:	learn: 0.0144486	total: 881ms	remaining: 319ms
734:	learn: 0.0144188	total: 882ms	remaining: 318ms
735:	learn: 0.0144070	total: 883ms	remaining: 317ms
736:	learn: 0.0143947	total: 884ms	remaining: 316ms
737:	learn: 0.0143709	total: 885ms	remaining: 314ms
738:	learn: 0.0143602	total: 887ms	remaining: 313ms
739:	learn: 0.0143360	total: 888ms	remaining: 312ms
740:	learn: 0.0143206	total: 889ms	remaining: 311ms
741:	learn: 0.0143086	total: 890ms	remaining: 309ms
742:	learn: 0.0142810	total: 891ms	remaining: 308ms
743:	learn: 0.0142629	total: 892ms	remaining: 307ms
744:	learn: 0.0142518	total: 893ms	remaining: 306ms
745:	learn: 0.0142291	total: 894ms	remaining: 304ms
746:	learn: 0.0141886	total: 895ms	remaining: 303ms
747:	learn: 0.0141735	total: 896ms	remaining: 302ms
748:	learn: 0.0141509	total: 897ms	remaining: 301ms
749:	learn: 0.0141334	total: 898ms	remaining: 299ms
750:	learn: 0.0141228	total: 899ms	remaining: 298ms
751:	learn: 0.0141082	total: 900ms	remaining: 297ms
752:	learn: 0.0140880	total: 900ms	remaining: 295ms
753:	learn: 0.0140588	total: 901ms	remaining: 294ms
754:	learn: 0.0140289	total: 902ms	remaining: 293ms
755:	learn: 0.0139973	total: 903ms	remaining: 292ms
756:	learn: 0.0139686	total: 904ms	remaining: 290ms
757:	learn: 0.0139475	total: 905ms	remaining: 289ms
758:	learn: 0.0139201	total: 906ms	remaining: 288ms
759:	learn: 0.0138818	total: 907ms	remaining: 286ms
760:	learn: 0.0138667	total: 909ms	remaining: 285ms
761:	learn: 0.0138565	total: 910ms	remaining: 284ms
762:	learn: 0.0138465	total: 911ms	remaining: 283ms
763:	learn: 0.0138261	total: 912ms	remaining: 282ms
764:	learn: 0.0138076	total: 914ms	remaining: 281ms
765:	learn: 0.0137801	total: 915ms	remaining: 280ms
766:	learn: 0.0137585	total: 916ms	remaining: 278ms
767:	learn: 0.0137289	total: 917ms	remaining: 277ms
768:	learn: 0.0137148	total: 918ms	remaining: 276ms
769:	learn: 0.0136975	total: 919ms	remaining: 275ms
770:	learn: 0.0136669	total: 920ms	remaining: 273ms

771:	learn: 0.0136576	total: 921ms	remaining: 272ms
772:	learn: 0.0136482	total: 923ms	remaining: 271ms
773:	learn: 0.0136366	total: 924ms	remaining: 270ms
774:	learn: 0.0136079	total: 925ms	remaining: 268ms
775:	learn: 0.0135787	total: 926ms	remaining: 267ms
776:	learn: 0.0135452	total: 927ms	remaining: 266ms
777:	learn: 0.0135295	total: 928ms	remaining: 265ms
778:	learn: 0.0135187	total: 929ms	remaining: 263ms
779:	learn: 0.0135001	total: 930ms	remaining: 262ms
780:	learn: 0.0134732	total: 931ms	remaining: 261ms
781:	learn: 0.0134522	total: 932ms	remaining: 260ms
782:	learn: 0.0134382	total: 933ms	remaining: 259ms
783:	learn: 0.0134241	total: 934ms	remaining: 257ms
784:	learn: 0.0133988	total: 935ms	remaining: 256ms
785:	learn: 0.0133802	total: 935ms	remaining: 255ms
786:	learn: 0.0133514	total: 936ms	remaining: 253ms
787:	learn: 0.0133362	total: 937ms	remaining: 252ms
788:	learn: 0.0133251	total: 939ms	remaining: 251ms
789:	learn: 0.0133045	total: 940ms	remaining: 250ms
790:	learn: 0.0132913	total: 941ms	remaining: 249ms
791:	learn: 0.0132728	total: 942ms	remaining: 247ms
792:	learn: 0.0132583	total: 943ms	remaining: 246ms
793:	learn: 0.0132442	total: 944ms	remaining: 245ms
794:	learn: 0.0132203	total: 945ms	remaining: 244ms
795:	learn: 0.0132008	total: 946ms	remaining: 242ms
796:	learn: 0.0131866	total: 946ms	remaining: 241ms
797:	learn: 0.0131711	total: 947ms	remaining: 240ms
798:	learn: 0.0131456	total: 948ms	remaining: 239ms
799:	learn: 0.0131332	total: 949ms	remaining: 237ms
800:	learn: 0.0131179	total: 951ms	remaining: 236ms
801:	learn: 0.0131035	total: 952ms	remaining: 235ms
802:	learn: 0.0130787	total: 953ms	remaining: 234ms
803:	learn: 0.0130675	total: 954ms	remaining: 233ms
804:	learn: 0.0130472	total: 955ms	remaining: 231ms
805:	learn: 0.0130392	total: 956ms	remaining: 230ms
806:	learn: 0.0130085	total: 957ms	remaining: 229ms
807:	learn: 0.0129896	total: 958ms	remaining: 228ms
808:	learn: 0.0129665	total: 959ms	remaining: 226ms
809:	learn: 0.0129494	total: 960ms	remaining: 225ms
810:	learn: 0.0129370	total: 961ms	remaining: 224ms
811:	learn: 0.0129119	total: 962ms	remaining: 223ms
812:	learn: 0.0128980	total: 963ms	remaining: 221ms
813:	learn: 0.0128850	total: 963ms	remaining: 220ms
814:	learn: 0.0128651	total: 964ms	remaining: 219ms
815:	learn: 0.0128523	total: 965ms	remaining: 218ms
816:	learn: 0.0128353	total: 966ms	remaining: 216ms
817:	learn: 0.0128196	total: 967ms	remaining: 215ms
818:	learn: 0.0128027	total: 968ms	remaining: 214ms
819:	learn: 0.0127788	total: 969ms	remaining: 213ms
820:	learn: 0.0127619	total: 970ms	remaining: 212ms
821:	learn: 0.0127442	total: 971ms	remaining: 210ms
822:	learn: 0.0127288	total: 972ms	remaining: 209ms
823:	learn: 0.0127012	total: 973ms	remaining: 208ms
824:	learn: 0.0126768	total: 974ms	remaining: 207ms
825:	learn: 0.0126676	total: 975ms	remaining: 205ms
826:	learn: 0.0126472	total: 976ms	remaining: 204ms
827:	learn: 0.0126365	total: 977ms	remaining: 203ms
828:	learn: 0.0125990	total: 978ms	remaining: 202ms
829:	learn: 0.0125851	total: 979ms	remaining: 200ms
830:	learn: 0.0125711	total: 980ms	remaining: 199ms
831:	learn: 0.0125492	total: 981ms	remaining: 198ms
832:	learn: 0.0125315	total: 982ms	remaining: 197ms
833:	learn: 0.0125141	total: 983ms	remaining: 196ms
834:	learn: 0.0124985	total: 985ms	remaining: 195ms
835:	learn: 0.0124875	total: 986ms	remaining: 193ms
836:	learn: 0.0124647	total: 986ms	remaining: 192ms
837:	learn: 0.0124385	total: 987ms	remaining: 191ms
838:	learn: 0.0124146	total: 988ms	remaining: 190ms
839:	learn: 0.0123988	total: 989ms	remaining: 188ms
840:	learn: 0.0123743	total: 990ms	remaining: 187ms
841:	learn: 0.0123662	total: 991ms	remaining: 186ms
842:	learn: 0.0123414	total: 992ms	remaining: 185ms
843:	learn: 0.0123316	total: 993ms	remaining: 183ms
844:	learn: 0.0123193	total: 994ms	remaining: 182ms
845:	learn: 0.0122960	total: 995ms	remaining: 181ms
846:	learn: 0.0122788	total: 996ms	remaining: 180ms
847:	learn: 0.0122625	total: 997ms	remaining: 179ms
848:	learn: 0.0122508	total: 997ms	remaining: 177ms
849:	learn: 0.0122440	total: 998ms	remaining: 176ms
850:	learn: 0.0122095	total: 999ms	remaining: 175ms
851:	learn: 0.0121954	total: 1s	remaining: 174ms
852:	learn: 0.0121618	total: 1s	remaining: 173ms
853:	learn: 0.0121469	total: 1s	remaining: 171ms
854:	learn: 0.0121334	total: 1s	remaining: 170ms
855:	learn: 0.0121210	total: 1s	remaining: 169ms
856:	learn: 0.0121091	total: 1s	remaining: 168ms
857:	learn: 0.0120988	total: 1.01s	remaining: 167ms
858:	learn: 0.0120865	total: 1.01s	remaining: 165ms
859:	learn: 0.0120538	total: 1.01s	remaining: 164ms
860:	learn: 0.0120331	total: 1.01s	remaining: 163ms
861:	learn: 0.0120113	total: 1.01s	remaining: 162ms
862:	learn: 0.0120007	total: 1.01s	remaining: 160ms
863:	learn: 0.0119875	total: 1.01s	remaining: 159ms
864:	learn: 0.0119760	total: 1.01s	remaining: 158ms
865:	learn: 0.0119644	total: 1.01s	remaining: 157ms
866:	learn: 0.0119532	total: 1.01s	remaining: 156ms
867:	learn: 0.0119377	total: 1.01s	remaining: 154ms
868:	learn: 0.0119268	total: 1.01s	remaining: 153ms
869:	learn: 0.0119192	total: 1.02s	remaining: 152ms
870:	learn: 0.0118991	total: 1.02s	remaining: 151ms
871:	learn: 0.0118764	total: 1.02s	remaining: 149ms
872:	learn: 0.0118544	total: 1.02s	remaining: 148ms
873:	learn: 0.0118435	total: 1.02s	remaining: 147ms
874:	learn: 0.0118087	total: 1.02s	remaining: 146ms
875:	learn: 0.0117965	total: 1.02s	remaining: 145ms
876:	learn: 0.0117821	total: 1.02s	remaining: 144ms
877:	learn: 0.0117690	total: 1.02s	remaining: 142ms
878:	learn: 0.0117469	total: 1.02s	remaining: 141ms
879:	learn: 0.0117350	total: 1.03s	remaining: 140ms
880:	learn: 0.0117256	total: 1.03s	remaining: 139ms
881:	learn: 0.0117162	total: 1.03s	remaining: 138ms
882:	learn: 0.0116936	total: 1.03s	remaining: 136ms
883:	learn: 0.0116798	total: 1.03s	remaining: 135ms
884:	learn: 0.0116654	total: 1.03s	remaining: 134ms
885:	learn: 0.0116539	total: 1.03s	remaining: 133ms
886:	learn: 0.0116467	total: 1.03s	remaining: 132ms
887:	learn: 0.0116313	total: 1.03s	remaining: 131ms
888:	learn: 0.0116203	total: 1.03s	remaining: 129ms
889:	learn: 0.0115928	total: 1.04s	remaining: 128ms
890:	learn: 0.0115755	total: 1.04s	remaining: 127ms
891:	learn: 0.0115664	total: 1.04s	remaining: 126ms
892:	learn: 0.0115526	total: 1.04s	remaining: 125ms
893:	learn: 0.0115345	total: 1.04s	remaining: 123ms
894:	learn: 0.0115223	total: 1.04s	remaining: 122ms
895:	learn: 0.0115121	total: 1.04s	remaining: 121ms
896:	learn: 0.0114932	total: 1.04s	remaining: 120ms
897:	learn: 0.0114731	total: 1.04s	remaining: 119ms
898:	learn: 0.0114514	total: 1.04s	remaining: 117ms
899:	learn: 0.0114367	total: 1.04s	remaining: 116ms
900:	learn: 0.0114156	total: 1.05s	remaining: 115ms
901:	learn: 0.0114033	total: 1.05s	remaining: 114ms
902:	learn: 0.0113956	total: 1.05s	remaining: 113ms
903:	learn: 0.0113872	total: 1.05s	remaining: 111ms
904:	learn: 0.0113775	total: 1.05s	remaining: 110ms
905:	learn: 0.0113577	total: 1.05s	remaining: 109ms
906:	learn: 0.0113354	total: 1.05s	remaining: 108ms
907:	learn: 0.0113110	total: 1.05s	remaining: 107ms
908:	learn: 0.0112920	total: 1.05s	remaining: 106ms
909:	learn: 0.0112783	total: 1.05s	remaining: 104ms
910:	learn: 0.0112682	total: 1.06s	remaining: 103ms
911:	learn: 0.0112508	total: 1.06s	remaining: 102ms
912:	learn: 0.0112431	total: 1.06s	remaining: 101ms
913:	learn: 0.0112357	total: 1.06s	remaining: 99.7ms
914:	learn: 0.0112236	total: 1.06s	remaining: 98.5ms
915:	learn: 0.0112161	total: 1.06s	remaining: 97.4ms
916:	learn: 0.0111966	total: 1.06s	remaining: 96.2ms
917:	learn: 0.0111824	total: 1.06s	remaining: 95ms
918:	learn: 0.0111617	total: 1.06s	remaining: 93.8ms
919:	learn: 0.0111449	total: 1.06s	remaining: 92.7ms
920:	learn: 0.0111272	total: 1.07s	remaining: 91.5ms
921:	learn: 0.0111148	total: 1.07s	remaining: 90.3ms
922:	learn: 0.0111051	total: 1.07s	remaining: 89.1ms
923:	learn: 0.0110921	total: 1.07s	remaining: 87.9ms
924:	learn: 0.0110838	total: 1.07s	remaining: 86.7ms
925:	learn: 0.0110707	total: 1.07s	remaining: 85.6ms
926:	learn: 0.0110513	total: 1.07s	remaining: 84.4ms
927:	learn: 0.0110429	total: 1.07s	remaining: 83.2ms
928:	learn: 0.0110326	total: 1.07s	remaining: 82ms
929:	learn: 0.0110137	total: 1.07s	remaining: 80.9ms
930:	learn: 0.0110051	total: 1.07s	remaining: 79.7ms
931:	learn: 0.0109980	total: 1.08s	remaining: 78.5ms
932:	learn: 0.0109862	total: 1.08s	remaining: 77.3ms
933:	learn: 0.0109766	total: 1.08s	remaining: 76.2ms
934:	learn: 0.0109695	total: 1.08s	remaining: 75ms
935:	learn: 0.0109430	total: 1.08s	remaining: 73.8ms
936:	learn: 0.0109251	total: 1.08s	remaining: 72.6ms
937:	learn: 0.0109184	total: 1.08s	remaining: 71.5ms
938:	learn: 0.0108875	total: 1.08s	remaining: 70.3ms
939:	learn: 0.0108681	total: 1.08s	remaining: 69.1ms
940:	learn: 0.0108455	total: 1.08s	remaining: 67.9ms
941:	learn: 0.0108317	total: 1.08s	remaining: 66.8ms
942:	learn: 0.0108204	total: 1.08s	remaining: 65.6ms
943:	learn: 0.0108133	total: 1.09s	remaining: 64.4ms
944:	learn: 0.0107938	total: 1.09s	remaining: 63.3ms
945:	learn: 0.0107840	total: 1.09s	remaining: 62.1ms
946:	learn: 0.0107723	total: 1.09s	remaining: 61ms
947:	learn: 0.0107539	total: 1.09s	remaining: 59.8ms
948:	learn: 0.0107269	total: 1.09s	remaining: 58.6ms
949:	learn: 0.0107166	total: 1.09s	remaining: 57.5ms
950:	learn: 0.0107069	total: 1.09s	remaining: 56.4ms
951:	learn: 0.0106806	total: 1.09s	remaining: 55.2ms
952:	learn: 0.0106660	total: 1.1s	remaining: 54.1ms
953:	learn: 0.0106532	total: 1.1s	remaining: 52.9ms
954:	learn: 0.0106396	total: 1.1s	remaining: 51.8ms
955:	learn: 0.0106220	total: 1.1s	remaining: 50.6ms
956:	learn: 0.0106115	total: 1.1s	remaining: 49.4ms
957:	learn: 0.0106060	total: 1.1s	remaining: 48.3ms
958:	learn: 0.0105996	total: 1.1s	remaining: 47.1ms
959:	learn: 0.0105805	total: 1.1s	remaining: 46ms
960:	learn: 0.0105619	total: 1.1s	remaining: 44.8ms

961:	learn: 0.0105528	total: 1.1s	remaining: 43.7ms
962:	learn: 0.0105372	total: 1.11s	remaining: 42.5ms
963:	learn: 0.0105309	total: 1.11s	remaining: 41.4ms
964:	learn: 0.0105118	total: 1.11s	remaining: 40.2ms
965:	learn: 0.0104876	total: 1.11s	remaining: 39.1ms
966:	learn: 0.0104704	total: 1.11s	remaining: 37.9ms
967:	learn: 0.0104636	total: 1.11s	remaining: 36.8ms
968:	learn: 0.0104524	total: 1.11s	remaining: 35.6ms
969:	learn: 0.0104339	total: 1.11s	remaining: 34.4ms
970:	learn: 0.0104117	total: 1.11s	remaining: 33.3ms
971:	learn: 0.0104002	total: 1.11s	remaining: 32.1ms
972:	learn: 0.0103840	total: 1.12s	remaining: 31ms
973:	learn: 0.0103607	total: 1.12s	remaining: 29.8ms
974:	learn: 0.0103460	total: 1.12s	remaining: 28.7ms
975:	learn: 0.0103356	total: 1.12s	remaining: 27.5ms
976:	learn: 0.0103183	total: 1.12s	remaining: 26.4ms
977:	learn: 0.0103016	total: 1.12s	remaining: 25.3ms
978:	learn: 0.0102940	total: 1.12s	remaining: 24.1ms
979:	learn: 0.0102846	total: 1.13s	remaining: 23ms
980:	learn: 0.0102694	total: 1.13s	remaining: 21.8ms
981:	learn: 0.0102490	total: 1.13s	remaining: 20.7ms
982:	learn: 0.0102368	total: 1.13s	remaining: 19.5ms
983:	learn: 0.0102283	total: 1.13s	remaining: 18.4ms
984:	learn: 0.0102209	total: 1.13s	remaining: 17.2ms
985:	learn: 0.0102053	total: 1.13s	remaining: 16.1ms
986:	learn: 0.0101932	total: 1.13s	remaining: 14.9ms
987:	learn: 0.0101758	total: 1.13s	remaining: 13.8ms
988:	learn: 0.0101674	total: 1.14s	remaining: 12.6ms
989:	learn: 0.0101511	total: 1.14s	remaining: 11.5ms
990:	learn: 0.0101374	total: 1.14s	remaining: 10.3ms
991:	learn: 0.0101307	total: 1.14s	remaining: 9.18ms
992:	learn: 0.0101222	total: 1.14s	remaining: 8.03ms
993:	learn: 0.0101084	total: 1.14s	remaining: 6.88ms
994:	learn: 0.0100963	total: 1.14s	remaining: 5.73ms
995:	learn: 0.0100793	total: 1.14s	remaining: 4.59ms
996:	learn: 0.0100684	total: 1.14s	remaining: 3.44ms
997:	learn: 0.0100604	total: 1.14s	remaining: 2.29ms
998:	learn: 0.0100469	total: 1.14s	remaining: 1.15ms
999:	learn: 0.0100359	total: 1.15s	remaining: 0us

In [57]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[101   1   0   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]

---------Accuracy Score------------
0.9980732177263969

---------Classification Report------------
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

    accuracy                           1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519

In [ ]:
pip

### Ensembel Voting Classifier

In [58]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [59]:
# create the sub models
estimators = []
model1 = DecisionTreeClassifier(criterion="gini", random_state=10)
estimators.append(('cart', model1))
model2 = SVC(kernel="rbf", C=50, gamma=0.1)
estimators.append(('svm', model2))
model3 = KNeighborsClassifier(n_neighbors=8)
estimators.append(('knn', model3))

In [60]:
estimators

[('cart', DecisionTreeClassifier(random_state=10)),
 ('svm', SVC(C=50, gamma=0.1)),
 ('knn', KNeighborsClassifier(n_neighbors=8))]

In [61]:
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,y_train)
y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [62]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[100   0   2   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

---------Accuracy Score------------
0.9903660886319846

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       102
           1       1.00      0.90      0.95        21
           2       0.99      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.96      0.98       519
weighted avg       0.99      0.99      0.99       519

# Conclusion

- based on above anlysis we can that the decision tree model performs better on test data