In [5]:
# Step 1 : conda create --name pro python==3.10
# Step 2 : conda activate pro
# Step 3 : pip install ipykernel
# Step 4 : python -m ipykernel install --user --name pro --display-name pro
# pip install kagglehub

In [16]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.preprocessing import (LabelEncoder, 
                                   StandardScaler, 
                                   MinMaxScaler)

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (confusion_matrix, 
                             accuracy_score,
                             classification_report)

In [14]:
# # Download latest version
# path = kagglehub.dataset_download("ruchikakumbhar/coupon-acception-prediction")
# print("Path to dataset files:", path)

In [17]:
df = pd.read_csv("coupon.csv")
print(df.shape)
df.head()

(12684, 25)

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,Bar,CoffeeHouse,CarryAway,Restaurant20,Restaurant20To50,dist_15,dist_25,direction_same,direction_opp,Y
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,never,never,NaN,4~8,1~3,0,0,0,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,never,never,NaN,4~8,1~3,0,0,0,1,0
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,never,never,NaN,4~8,1~3,1,0,0,1,1
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,never,never,NaN,4~8,1~3,1,0,0,1,0
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,never,never,NaN,4~8,1~3,1,0,0,1,0

In [18]:
df.isnull().sum()

destination             0
passanger               0
weather                 0
temperature             0
time                    0
coupon                  0
expiration              0
gender                  0
age                     0
maritalStatus           0
children                0
education               0
occupation              0
income                  0
car                 12576
Bar                   107
CoffeeHouse           217
CarryAway             151
Restaurant20          130
Restaurant20To50      189
dist_15                 0
dist_25                 0
direction_same          0
direction_opp           0
Y                       0
dtype: int64

In [19]:
df = df.drop("car", axis=1)

miss_data = ["Bar", "CoffeeHouse", "CarryAway", "Restaurant20", "Restaurant20To50"]

for col in miss_data:
    mode = df[col].mode().iloc[0]
    df[col].fillna(mode, inplace=True)
    
df.isnull().sum()

C:\Users\Dev\AppData\Local\Temp\ipykernel_3248\1107442157.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode, inplace=True)

destination         0
passanger           0
weather             0
temperature         0
time                0
coupon              0
expiration          0
gender              0
age                 0
maritalStatus       0
children            0
education           0
occupation          0
income              0
Bar                 0
CoffeeHouse         0
CarryAway           0
Restaurant20        0
Restaurant20To50    0
dist_15             0
dist_25             0
direction_same      0
direction_opp       0
Y                   0
dtype: int64

In [20]:
# check category level of all columns
for col in df.columns:
    print("----------------{}-----------------------".format(col))
    print(df[col].value_counts())
    print()

----------------destination-----------------------
destination
No Urgent Place    6283
Home               3237
Work               3164
Name: count, dtype: int64

----------------passanger-----------------------
passanger
Alone        7305
Friend(s)    3298
Partner      1075
Kid(s)       1006
Name: count, dtype: int64

----------------weather-----------------------
weather
Sunny    10069
Snowy     1405
Rainy     1210
Name: count, dtype: int64

----------------temperature-----------------------
temperature
80    6528
55    3840
30    2316
Name: count, dtype: int64

----------------time-----------------------
time
6PM     3230
7AM     3164
10AM    2275
2PM     2009
10PM    2006
Name: count, dtype: int64

----------------coupon-----------------------
coupon
Coffee House             3996
Restaurant(<20)          2786
Carry out & Take away    2393
Bar                      2017
Restaurant(20-50)        1492
Name: count, dtype: int64

----------------expiration-----------------------
expiration
1d    7091
2h    5593
Name: count, dtype: int64

----------------gender-----------------------
gender
Female    6511
Male      6173
Name: count, dtype: int64

----------------age-----------------------
age
21         2653
26         2559
31         2039
50plus     1788
36         1319
41         1093
46          686
below21     547
Name: count, dtype: int64

----------------maritalStatus-----------------------
maritalStatus
Married partner      5100
Single               4752
Unmarried partner    2186
Divorced              516
Widowed               130
Name: count, dtype: int64

----------------children-----------------------
children
0    7431
1    5253
Name: count, dtype: int64

----------------education-----------------------
education
Some college - no degree                  4351
Bachelors degree                          4335
Graduate degree (Masters or Doctorate)    1852
Associates degree                         1153
High School Graduate                       905
Some High School                            88
Name: count, dtype: int64

----------------occupation-----------------------
occupation
Unemployed                                   1870
Student                                      1584
Computer & Mathematical                      1408
Sales & Related                              1093
Education&Training&Library                    943
Management                                    838
Office & Administrative Support               639
Arts Design Entertainment Sports & Media      629
Business & Financial                          544
Retired                                       495
Food Preparation & Serving Related            298
Healthcare Practitioners & Technical          244
Healthcare Support                            242
Community & Social Services                   241
Legal                                         219
Transportation & Material Moving              218
Architecture & Engineering                    175
Personal Care & Service                       175
Protective Service                            175
Life Physical Social Science                  170
Construction & Extraction                     154
Installation Maintenance & Repair             133
Production Occupations                        110
Building & Grounds Cleaning & Maintenance      44
Farming Fishing & Forestry                     43
Name: count, dtype: int64

----------------income-----------------------
income
$25000 - $37499     2013
$12500 - $24999     1831
$37500 - $49999     1805
$100000 or More     1736
$50000 - $62499     1659
Less than $12500    1042
$87500 - $99999      895
$75000 - $87499      857
$62500 - $74999      846
Name: count, dtype: int64

----------------Bar-----------------------
Bar
never    5304
less1    3482
1~3      2473
4~8      1076
gt8       349
Name: count, dtype: int64

----------------CoffeeHouse-----------------------
CoffeeHouse
less1    3602
1~3      3225
never    2962
4~8      1784
gt8      1111
Name: count, dtype: int64

----------------CarryAway-----------------------
CarryAway
1~3      4823
4~8      4258
less1    1856
gt8      1594
never     153
Name: count, dtype: int64

----------------Restaurant20-----------------------
Restaurant20
1~3      5506
4~8      3580
less1    2093
gt8      1285
never     220
Name: count, dtype: int64

----------------Restaurant20To50-----------------------
Restaurant20To50
less1    6266
1~3      3290
never    2136
4~8       728
gt8       264
Name: count, dtype: int64

----------------dist_15-----------------------
dist_15
1    7122
0    5562
Name: count, dtype: int64

----------------dist_25-----------------------
dist_25
0    11173
1     1511
Name: count, dtype: int64

----------------direction_same-----------------------
direction_same
0    9960
1    2724
Name: count, dtype: int64

----------------direction_opp-----------------------
direction_opp
1    9960
0    2724
Name: count, dtype: int64

----------------Y-----------------------
Y
1    7210
0    5474
Name: count, dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12684 entries, 0 to 12683
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   destination       12684 non-null  object
 1   passanger         12684 non-null  object
 2   weather           12684 non-null  object
 3   temperature       12684 non-null  int64
 4   time              12684 non-null  object
 5   coupon            12684 non-null  object
 6   expiration        12684 non-null  object
 7   gender            12684 non-null  object
 8   age               12684 non-null  object
 9   maritalStatus     12684 non-null  object
 10  children          12684 non-null  int64
 11  education         12684 non-null  object
 12  occupation        12684 non-null  object
 13  income            12684 non-null  object
 14  Bar               12684 non-null  object
 15  CoffeeHouse       12684 non-null  object
 16  CarryAway         12684 non-null  object
 17  Restaurant20      12684 non-null  object
 18  Restaurant20To50  12684 non-null  object
 19  dist_15           12684 non-null  int64
 20  dist_25           12684 non-null  int64
 21  direction_same    12684 non-null  int64
 22  direction_opp     12684 non-null  int64
 23  Y                 12684 non-null  int64
dtypes: int64(7), object(17)
memory usage: 2.3+ MB

In [23]:
# apply label encoder to convert categories into numeric values
le = LabelEncoder()

for x in df.columns:
    
    if df[x].dtypes == "object":
        print(x)
        df[x]=le.fit_transform(df[x])
        le_name = dict(zip(le.classes_, le.transform(le.classes_)))
        print("--------------------------------------------------")
        print("Feature: ", x)
        print("Mapping: ", le_name)

destination
--------------------------------------------------
Feature:  destination
Mapping:  {'Home': np.int64(0), 'No Urgent Place': np.int64(1), 'Work': np.int64(2)}
passanger
--------------------------------------------------
Feature:  passanger
Mapping:  {'Alone': np.int64(0), 'Friend(s)': np.int64(1), 'Kid(s)': np.int64(2), 'Partner': np.int64(3)}
weather
--------------------------------------------------
Feature:  weather
Mapping:  {'Rainy': np.int64(0), 'Snowy': np.int64(1), 'Sunny': np.int64(2)}
time
--------------------------------------------------
Feature:  time
Mapping:  {'10AM': np.int64(0), '10PM': np.int64(1), '2PM': np.int64(2), '6PM': np.int64(3), '7AM': np.int64(4)}
coupon
--------------------------------------------------
Feature:  coupon
Mapping:  {'Bar': np.int64(0), 'Carry out & Take away': np.int64(1), 'Coffee House': np.int64(2), 'Restaurant(20-50)': np.int64(3), 'Restaurant(<20)': np.int64(4)}
expiration
--------------------------------------------------
Feature:  expiration
Mapping:  {'1d': np.int64(0), '2h': np.int64(1)}
gender
--------------------------------------------------
Feature:  gender
Mapping:  {'Female': np.int64(0), 'Male': np.int64(1)}
age
--------------------------------------------------
Feature:  age
Mapping:  {'21': np.int64(0), '26': np.int64(1), '31': np.int64(2), '36': np.int64(3), '41': np.int64(4), '46': np.int64(5), '50plus': np.int64(6), 'below21': np.int64(7)}
maritalStatus
--------------------------------------------------
Feature:  maritalStatus
Mapping:  {'Divorced': np.int64(0), 'Married partner': np.int64(1), 'Single': np.int64(2), 'Unmarried partner': np.int64(3), 'Widowed': np.int64(4)}
education
--------------------------------------------------
Feature:  education
Mapping:  {'Associates degree': np.int64(0), 'Bachelors degree': np.int64(1), 'Graduate degree (Masters or Doctorate)': np.int64(2), 'High School Graduate': np.int64(3), 'Some High School': np.int64(4), 'Some college - no degree': np.int64(5)}
occupation
--------------------------------------------------
Feature:  occupation
Mapping:  {'Architecture & Engineering': np.int64(0), 'Arts Design Entertainment Sports & Media': np.int64(1), 'Building & Grounds Cleaning & Maintenance': np.int64(2), 'Business & Financial': np.int64(3), 'Community & Social Services': np.int64(4), 'Computer & Mathematical': np.int64(5), 'Construction & Extraction': np.int64(6), 'Education&Training&Library': np.int64(7), 'Farming Fishing & Forestry': np.int64(8), 'Food Preparation & Serving Related': np.int64(9), 'Healthcare Practitioners & Technical': np.int64(10), 'Healthcare Support': np.int64(11), 'Installation Maintenance & Repair': np.int64(12), 'Legal': np.int64(13), 'Life Physical Social Science': np.int64(14), 'Management': np.int64(15), 'Office & Administrative Support': np.int64(16), 'Personal Care & Service': np.int64(17), 'Production Occupations': np.int64(18), 'Protective Service': np.int64(19), 'Retired': np.int64(20), 'Sales & Related': np.int64(21), 'Student': np.int64(22), 'Transportation & Material Moving': np.int64(23), 'Unemployed': np.int64(24)}
income
--------------------------------------------------
Feature:  income
Mapping:  {'$100000 or More': np.int64(0), '$12500 - $24999': np.int64(1), '$25000 - $37499': np.int64(2), '$37500 - $49999': np.int64(3), '$50000 - $62499': np.int64(4), '$62500 - $74999': np.int64(5), '$75000 - $87499': np.int64(6), '$87500 - $99999': np.int64(7), 'Less than $12500': np.int64(8)}
Bar
--------------------------------------------------
Feature:  Bar
Mapping:  {'1~3': np.int64(0), '4~8': np.int64(1), 'gt8': np.int64(2), 'less1': np.int64(3), 'never': np.int64(4)}
CoffeeHouse
--------------------------------------------------
Feature:  CoffeeHouse
Mapping:  {'1~3': np.int64(0), '4~8': np.int64(1), 'gt8': np.int64(2), 'less1': np.int64(3), 'never': np.int64(4)}
CarryAway
--------------------------------------------------
Feature:  CarryAway
Mapping:  {'1~3': np.int64(0), '4~8': np.int64(1), 'gt8': np.int64(2), 'less1': np.int64(3), 'never': np.int64(4)}
Restaurant20
--------------------------------------------------
Feature:  Restaurant20
Mapping:  {'1~3': np.int64(0), '4~8': np.int64(1), 'gt8': np.int64(2), 'less1': np.int64(3), 'never': np.int64(4)}
Restaurant20To50
--------------------------------------------------
Feature:  Restaurant20To50
Mapping:  {'1~3': np.int64(0), '4~8': np.int64(1), 'gt8': np.int64(2), 'less1': np.int64(3), 'never': np.int64(4)}

In [24]:
df.head()

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,Bar,CoffeeHouse,CarryAway,Restaurant20,Restaurant20To50,dist_15,dist_25,direction_same,direction_opp,Y
0,1,0,2,55,2,4,0,0,0,3,...,4,4,0,1,0,0,0,0,1,1
1,1,1,2,80,0,2,1,0,0,3,...,4,4,0,1,0,0,0,0,1,0
2,1,1,2,80,0,1,1,0,0,3,...,4,4,0,1,0,1,0,0,1,1
3,1,1,2,80,2,2,1,0,0,3,...,4,4,0,1,0,1,0,0,1,0
4,1,1,2,80,2,2,0,0,0,3,...,4,4,0,1,0,1,0,0,1,0

In [27]:
X = df.iloc[  :  ,  :-1]  # independent variables
y = df.iloc[  :  ,   -1] 

# Split the data into test and train
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3,
                                                    random_state=10)  
# verify spliting data
print("Total Data: ", df.shape)
print("Train X: ", X_train.shape)
print("Train y: ", y_train.shape)
print("Test X: ", X_test.shape)
print("Test y: ", y_test.shape)

# perform data normalisation

# create object for scaler
scaler = MinMaxScaler()

# fit the train data on scaler object 
scaler.fit(X_train)

X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)

Total Data:  (12684, 24)
Train X:  (8878, 23)
Train y:  (8878,)
Test X:  (3806, 23)
Test y:  (3806,)

In [38]:
from sklearn.ensemble import (BaggingClassifier, 
                              RandomForestClassifier, 
                              AdaBoostClassifier, 
                              GradientBoostingClassifier)
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# from catboost import catboost

In [39]:
def build_ensembel_model(X_train, X_test, y_train, y_test):
    
    model_list = []
    
    m1 = BaggingClassifier()
    m2 = RandomForestClassifier()
    m3 = AdaBoostClassifier()
    m4 = GradientBoostingClassifier()
    m5 = DecisionTreeClassifier()
    m6 = LogisticRegression()
    m7 = SVC()
#     m8 = catboost()
    
    model_list.append(("Bagging Model", m1))
    model_list.append(("RandomForest Model", m2))
    model_list.append(("Adaboost Model", m3))
    model_list.append(("GradientBoost Model", m4))
    model_list.append(("DecisionTree Model", m5))
    model_list.append(("LogisticRegression Model", m6))
    model_list.append(("Svc Model", m7))
#     model_list.append(("Catboost", m8))
    
    results = []
    for name, model in model_list:
        print("Training {} ...............".format(name))    
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        
        
        print("---------Confusion Matrix------------")
        print(confusion_matrix(y_test, y_pred))
        print()
        print("---------Accuracy Score------------")
        print(accuracy_score(y_test,y_pred))
        print()
        print("---------Classification Report------------")
        print(classification_report(y_test,y_pred))

        print("Model Training Complete............")
        print()

In [40]:
build_ensembel_model(X_train_scale, X_test_scale, y_train, y_test)

Training Bagging Model ...............
---------Confusion Matrix------------
[[1146  536]
 [ 563 1561]]

---------Accuracy Score------------
0.711245401996847

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.67      0.68      0.68      1682
           1       0.74      0.73      0.74      2124

    accuracy                           0.71      3806
   macro avg       0.71      0.71      0.71      3806
weighted avg       0.71      0.71      0.71      3806

Model Training Complete............

Training RandomForest Model ...............
---------Confusion Matrix------------
[[1106  576]
 [ 381 1743]]

---------Accuracy Score------------
0.7485549132947977

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.74      0.66      0.70      1682
           1       0.75      0.82      0.78      2124

    accuracy                           0.75      3806
   macro avg       0.75      0.74      0.74      3806
weighted avg       0.75      0.75      0.75      3806

Model Training Complete............

Training Adaboost Model ...............
---------Confusion Matrix------------
[[ 917  765]
 [ 456 1668]]

---------Accuracy Score------------
0.6791907514450867

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.67      0.55      0.60      1682
           1       0.69      0.79      0.73      2124

    accuracy                           0.68      3806
   macro avg       0.68      0.67      0.67      3806
weighted avg       0.68      0.68      0.67      3806

Model Training Complete............

Training GradientBoost Model ...............
---------Confusion Matrix------------
[[ 987  695]
 [ 378 1746]]

---------Accuracy Score------------
0.7180767209668943

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.72      0.59      0.65      1682
           1       0.72      0.82      0.76      2124

    accuracy                           0.72      3806
   macro avg       0.72      0.70      0.71      3806
weighted avg       0.72      0.72      0.71      3806

Model Training Complete............

Training DecisionTree Model ...............
---------Confusion Matrix------------
[[1037  645]
 [ 562 1562]]

---------Accuracy Score------------
0.6828691539674199

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.65      0.62      0.63      1682
           1       0.71      0.74      0.72      2124

    accuracy                           0.68      3806
   macro avg       0.68      0.68      0.68      3806
weighted avg       0.68      0.68      0.68      3806

Model Training Complete............

Training LogisticRegression Model ...............
---------Confusion Matrix------------
[[ 712  970]
 [ 474 1650]]

---------Accuracy Score------------
0.6205990541250657

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.60      0.42      0.50      1682
           1       0.63      0.78      0.70      2124

    accuracy                           0.62      3806
   macro avg       0.62      0.60      0.60      3806
weighted avg       0.62      0.62      0.61      3806

Model Training Complete............

Training Svc Model ...............
---------Confusion Matrix------------
[[ 854  828]
 [ 400 1724]]

---------Accuracy Score------------
0.6773515501839201

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.68      0.51      0.58      1682
           1       0.68      0.81      0.74      2124

    accuracy                           0.68      3806
   macro avg       0.68      0.66      0.66      3806
weighted avg       0.68      0.68      0.67      3806

Model Training Complete............

## Lazypredict

In [41]:
from lazypredict.Supervised import LazyClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [42]:
clf = LazyClassifier(verbose=1,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train_scale, X_test_scale, y_train, y_test)

  3%|██▌                                                                                | 1/32 [00:00<00:10,  2.95it/s]

{'Model': 'AdaBoostClassifier', 'Accuracy': 0.6791907514450867, 'Balanced Accuracy': np.float64(0.6652475194314006), 'ROC AUC': np.float64(0.6652475194314006), 'F1 Score': 0.6738431989909099, 'Time taken': 0.33746767044067383}

 12%|██████████▍                                                                        | 4/32 [00:00<00:04,  5.76it/s]

{'Model': 'BaggingClassifier', 'Accuracy': 0.7233315817130846, 'Balanced Accuracy': np.float64(0.7208792106966193), 'ROC AUC': np.float64(0.7208792106966193), 'F1 Score': 0.7236629132727188, 'Time taken': 0.30785393714904785}
{'Model': 'BernoulliNB', 'Accuracy': 0.6192853389385181, 'Balanced Accuracy': np.float64(0.599821752867965), 'ROC AUC': np.float64(0.599821752867965), 'F1 Score': 0.6076918927396615, 'Time taken': 0.034064531326293945}
{'Model': 'CalibratedClassifierCV', 'Accuracy': 0.6211245401996847, 'Balanced Accuracy': np.float64(0.5998612202762831), 'ROC AUC': np.float64(0.5998612202762831), 'F1 Score': 0.6071476982780873, 'Time taken': 0.1360323429107666}

 22%|██████████████████▏                                                                | 7/32 [00:00<00:02, 10.26it/s]

{'Model': 'DecisionTreeClassifier', 'Accuracy': 0.6820809248554913, 'Balanced Accuracy': np.float64(0.6756932268329112), 'ROC AUC': np.float64(0.6756932268329112), 'F1 Score': 0.6813317323192353, 'Time taken': 0.07427453994750977}
{'Model': 'DummyClassifier', 'Accuracy': 0.558066211245402, 'Balanced Accuracy': np.float64(0.5), 'ROC AUC': np.float64(0.5), 'F1 Score': 0.39977491827495243, 'Time taken': 0.03097987174987793}
{'Model': 'ExtraTreeClassifier', 'Accuracy': 0.6558066211245402, 'Balanced Accuracy': np.float64(0.6497401868907744), 'ROC AUC': np.float64(0.6497401868907744), 'F1 Score': 0.6552900933723007, 'Time taken': 0.04494285583496094}

 28%|███████████████████████▎                                                           | 9/32 [00:02<00:07,  3.03it/s]

{'Model': 'ExtraTreesClassifier', 'Accuracy': 0.7293746715712034, 'Balanced Accuracy': np.float64(0.719983776375985), 'ROC AUC': np.float64(0.719983776375985), 'F1 Score': 0.7271629333388409, 'Time taken': 1.4678194522857666}
{'Model': 'GaussianNB', 'Accuracy': 0.5990541250656858, 'Balanced Accuracy': np.float64(0.5751383878487407), 'ROC AUC': np.float64(0.5751383878487407), 'F1 Score': 0.5805546611829816, 'Time taken': 0.04675626754760742}

 38%|██████████████████████████████▊                                                   | 12/32 [00:03<00:05,  3.34it/s]

{'Model': 'KNeighborsClassifier', 'Accuracy': 0.6439831844456122, 'Balanced Accuracy': np.float64(0.6320330361801371), 'ROC AUC': np.float64(0.6320330361801371), 'F1 Score': 0.6400855251448749, 'Time taken': 0.7298364639282227}

 41%|█████████████████████████████████▎                                                | 13/32 [00:09<00:24,  1.31s/it]

{'Model': 'LabelPropagation', 'Accuracy': 0.6184971098265896, 'Balanced Accuracy': np.float64(0.6120443333758798), 'ROC AUC': np.float64(0.6120443333758797), 'F1 Score': 0.6179810630493533, 'Time taken': 6.204335927963257}

 50%|█████████████████████████████████████████                                         | 16/32 [00:16<00:25,  1.57s/it]

{'Model': 'LabelSpreading', 'Accuracy': 0.6182343667892801, 'Balanced Accuracy': np.float64(0.6115614874230526), 'ROC AUC': np.float64(0.6115614874230526), 'F1 Score': 0.617618488481632, 'Time taken': 6.959778547286987}
{'Model': 'LinearDiscriminantAnalysis', 'Accuracy': 0.6187598528638991, 'Balanced Accuracy': np.float64(0.5983611788494998), 'ROC AUC': np.float64(0.5983611788494998), 'F1 Score': 0.6059324294711521, 'Time taken': 0.060625314712524414}
{'Model': 'LinearSVC', 'Accuracy': 0.6200735680504467, 'Balanced Accuracy': np.float64(0.5994144828034064), 'ROC AUC': np.float64(0.5994144828034064), 'F1 Score': 0.60691414974728, 'Time taken': 0.04289698600769043}
{'Model': 'LogisticRegression', 'Accuracy': 0.6200735680504467, 'Balanced Accuracy': np.float64(0.5996619238598118), 'ROC AUC': np.float64(0.5996619238598118), 'F1 Score': 0.6072488238726353, 'Time taken': 0.045738935470581055}
{'Model': 'NearestCentroid', 'Accuracy': 0.6127167630057804, 'Balanced Accuracy': np.float64(0.608102630936626), 'ROC AUC': np.float64(0.608102630936626), 'F1 Score': 0.612966846036756, 'Time taken': 0.025051355361938477}

 69%|████████████████████████████████████████████████████████▍                         | 22/32 [00:23<00:11,  1.16s/it]

{'Model': 'NuSVC', 'Accuracy': 0.7028376248029428, 'Balanced Accuracy': np.float64(0.6945995149707438), 'ROC AUC': np.float64(0.6945995149707437), 'F1 Score': 0.7012020745710348, 'Time taken': 6.562429666519165}
{'Model': 'PassiveAggressiveClassifier', 'Accuracy': 0.5630583289542828, 'Balanced Accuracy': np.float64(0.5509297513721222), 'ROC AUC': np.float64(0.5509297513721222), 'F1 Score': 0.5590983422534898, 'Time taken': 0.052236080169677734}
{'Model': 'Perceptron', 'Accuracy': 0.5648975302154493, 'Balanced Accuracy': np.float64(0.5596915160187294), 'ROC AUC': np.float64(0.5596915160187295), 'F1 Score': 0.5652025385878632, 'Time taken': 0.03470206260681152}
{'Model': 'QuadraticDiscriminantAnalysis', 'Accuracy': 0.6095638465580662, 'Balanced Accuracy': np.float64(0.5895034048337219), 'ROC AUC': np.float64(0.5895034048337219), 'F1 Score': 0.5970585907081996, 'Time taken': 0.04601550102233887}

 81%|██████████████████████████████████████████████████████████████████▋               | 26/32 [00:24<00:04,  1.37it/s]

{'Model': 'RandomForestClassifier', 'Accuracy': 0.7409353652128219, 'Balanced Accuracy': np.float64(0.7314550765723704), 'ROC AUC': np.float64(0.7314550765723703), 'F1 Score': 0.738696218919852, 'Time taken': 1.009314775466919}
{'Model': 'RidgeClassifier', 'Accuracy': 0.6200735680504467, 'Balanced Accuracy': np.float64(0.5994144828034064), 'ROC AUC': np.float64(0.5994144828034064), 'F1 Score': 0.60691414974728, 'Time taken': 0.03071451187133789}
{'Model': 'RidgeClassifierCV', 'Accuracy': 0.6203363110877562, 'Balanced Accuracy': np.float64(0.5996498876998282), 'ROC AUC': np.float64(0.5996498876998282), 'F1 Score': 0.6071438760547752, 'Time taken': 0.043799400329589844}
{'Model': 'SGDClassifier', 'Accuracy': 0.581187598528639, 'Balanced Accuracy': np.float64(0.5650075799816827), 'ROC AUC': np.float64(0.5650075799816827), 'F1 Score': 0.5732309923626915, 'Time taken': 0.07938694953918457}

 88%|███████████████████████████████████████████████████████████████████████▊          | 28/32 [00:29<00:05,  1.30s/it]

{'Model': 'SVC', 'Accuracy': 0.6873357856016815, 'Balanced Accuracy': np.float64(0.6707511235615389), 'ROC AUC': np.float64(0.670751123561539), 'F1 Score': 0.6797501813146067, 'Time taken': 5.446794509887695}

100%|██████████████████████████████████████████████████████████████████████████████████| 32/32 [00:30<00:00,  1.05it/s]

[LightGBM] [Info] Number of positive: 5086, number of negative: 3792
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000885 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 138
[LightGBM] [Info] Number of data points in the train set: 8878, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.572877 -> initscore=0.293598
[LightGBM] [Info] Start training from score 0.293598
{'Model': 'LGBMClassifier', 'Accuracy': 0.7477666841828692, 'Balanced Accuracy': np.float64(0.7370807217665276), 'ROC AUC': np.float64(0.7370807217665276), 'F1 Score': 0.744922558312742, 'Time taken': 0.17917990684509277}

In [43]:
models

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
LGBMClassifier,0.75,0.74,0.74,0.74,0.18
RandomForestClassifier,0.74,0.73,0.73,0.74,1.01
BaggingClassifier,0.72,0.72,0.72,0.72,0.31
ExtraTreesClassifier,0.73,0.72,0.72,0.73,1.47
NuSVC,0.70,0.69,0.69,0.70,6.56
DecisionTreeClassifier,0.68,0.68,0.68,0.68,0.07
SVC,0.69,0.67,0.67,0.68,5.45
AdaBoostClassifier,0.68,0.67,0.67,0.67,0.34
ExtraTreeClassifier,0.66,0.65,0.65,0.66,0.04
KNeighborsClassifier,0.64,0.63,0.63,0.64,0.73
LabelPropagation,0.62,0.61,0.61,0.62,6.20
LabelSpreading,0.62,0.61,0.61,0.62,6.96
NearestCentroid,0.61,0.61,0.61,0.61,0.03
CalibratedClassifierCV,0.62,0.60,0.60,0.61,0.14
BernoulliNB,0.62,0.60,0.60,0.61,0.03
LogisticRegression,0.62,0.60,0.60,0.61,0.05
RidgeClassifierCV,0.62,0.60,0.60,0.61,0.04
RidgeClassifier,0.62,0.60,0.60,0.61,0.03
LinearSVC,0.62,0.60,0.60,0.61,0.04
LinearDiscriminantAnalysis,0.62,0.60,0.60,0.61,0.06
QuadraticDiscriminantAnalysis,0.61,0.59,0.59,0.60,0.05
GaussianNB,0.60,0.58,0.58,0.58,0.05
SGDClassifier,0.58,0.57,0.57,0.57,0.08
Perceptron,0.56,0.56,0.56,0.57,0.03
PassiveAggressiveClassifier,0.56,0.55,0.55,0.56,0.05
DummyClassifier,0.56,0.50,0.50,0.40,0.03

In [44]:
predictions

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
LGBMClassifier,0.75,0.74,0.74,0.74,0.18
RandomForestClassifier,0.74,0.73,0.73,0.74,1.01
BaggingClassifier,0.72,0.72,0.72,0.72,0.31
ExtraTreesClassifier,0.73,0.72,0.72,0.73,1.47
NuSVC,0.70,0.69,0.69,0.70,6.56
DecisionTreeClassifier,0.68,0.68,0.68,0.68,0.07
SVC,0.69,0.67,0.67,0.68,5.45
AdaBoostClassifier,0.68,0.67,0.67,0.67,0.34
ExtraTreeClassifier,0.66,0.65,0.65,0.66,0.04
KNeighborsClassifier,0.64,0.63,0.63,0.64,0.73
LabelPropagation,0.62,0.61,0.61,0.62,6.20
LabelSpreading,0.62,0.61,0.61,0.62,6.96
NearestCentroid,0.61,0.61,0.61,0.61,0.03
CalibratedClassifierCV,0.62,0.60,0.60,0.61,0.14
BernoulliNB,0.62,0.60,0.60,0.61,0.03
LogisticRegression,0.62,0.60,0.60,0.61,0.05
RidgeClassifierCV,0.62,0.60,0.60,0.61,0.04
RidgeClassifier,0.62,0.60,0.60,0.61,0.03
LinearSVC,0.62,0.60,0.60,0.61,0.04
LinearDiscriminantAnalysis,0.62,0.60,0.60,0.61,0.06
QuadraticDiscriminantAnalysis,0.61,0.59,0.59,0.60,0.05
GaussianNB,0.60,0.58,0.58,0.58,0.05
SGDClassifier,0.58,0.57,0.57,0.57,0.08
Perceptron,0.56,0.56,0.56,0.57,0.03
PassiveAggressiveClassifier,0.56,0.55,0.55,0.56,0.05
DummyClassifier,0.56,0.50,0.50,0.40,0.03